### ISSUE TITLE
Wiki cleanup

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#1]
Although all of the content has been migrated from the Bitbucket wiki, there are some syntax differences and functionality differences that need to be addressed. In particular:

- [x] Add a side-bar TOC for the documentation as a whole
- [x] Add manually created subsection TOCs to replace the <<toc>> syntax that Bitbucket supported
- [x] Fix up external URL links that appear to be broken here on GH
- [x] Either fix up or else remove the links to previous versions of the docs (not sure that there is a way of linking to a tagged version of the wiki).
- [x] Fix up or remove the code block syntax

Ideally I would also like to move all the pages over to using either Markdown or reStructuredText as these are the formats that I'm more familiar with.

**Comment by tpluscode** [comment]
Hm, I'm guessing you simply copied the latest state of the wiki from BB to GH? Would you mind if I converted the entire repository together with history? This should give us the historical pages for past versions similar as on Bitbucket

**Comment by kal** [comment]
I think it is just that the Wiki UI on GH doesn't properly show the history. 

If you clone from https://github.com/dotnetrdf/dotnetrdf.wiki.git you will see that the history is there if you use git log...
