### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by saksten** [dotnetrdf/dotnetrdf#110]
In Library Overveiw in the wiki (https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Library-Overview) in the Triple Store-section there is a typo in the second paragraph's last sentence: _This interface defines properties and methods relating to adding & removing Graphs and the retrieval **or** Graphs and Triples contained in the Store._

Should be "of" instead of "or".

Also in https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Working-With-Graphs Base Uri-section second sentence: _A Base URI **if** the URI against which any relative URIs are..._

Should be "is" instead of "if"

**Comment by tpluscode** [comment]
Fixed. Thanks for spotting these!
