### ISSUE TITLE
SparqlParameterizedString does not recognize default namespace unless it is listed last

### ISSUE THREAD

**Issue by christopheralcock** [dotnetrdf/dotnetrdf#111]
Strange error I've noticed today is that if you include more than one PREFIX statement in a sparql query string, dotnetrdf denies that you've stated the default (`PREFIX :`) namespace, unless you state it after all other prefixes.
Work-around is easy, but this seems like a very strange bug to me.

**Comment by kal** [comment]
Fixed in PRs #113 and #115
