### ISSUE TITLE
How to use .ToLiteral() for typed literal-nodes

### ISSUE THREAD

**Issue by saksten** [dotnetrdf/dotnetrdf#112]
In the wiki (https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Typed-Values-And-Lists) the usage is: 

```
//Assuming we have a Graph in variable g already
INode intNode = (12345).ToLiteral(g);
INode dateNode = DateTime.Now.ToLiteral(g);
```

but I have version  1.0.12 and when I'm trying DateTime.Now.ToLiteral() it wants a NodeFactory as a parameter. If a use a NodeFactory as parameter then I get an error when trying to create the a triple (_`Subject, Predicate and Object Nodes must all come from the same Graph/Node Factory - use Tools.CopyNode() to transfer nodes between Graphs`_) because the other nodes in the triple have been created with the graph g.CreateXNode(). 

How can i use .ToLiteral() ?

**Comment by rvesse** [comment]
Any `IGraph` instance is a `INodeFactory` instance so simply pass in your existing graph object to `ToLiteral()` as shown in the example
