### ISSUE TITLE
AppVeyor pull request hook broke?

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#114]
@kal did the PR hook stop working? I don't think the two recent pull requests were picked up by AppVeyor, were they?

**Comment by kal** [comment]
It looks like it is. But it worked fine for my PR from a feature branch, so it looks like it may either be a really recent breakage or it is related to receiving a PR from a repo clone? 

I just noticed that the default branch in the AppVeyor project configuration (through the web UI) is set to netcore-reorg, so I've changed that to master...but I don't see what changing that would make a difference.

**Comment by kal** [comment]
Just did another PR from a feature branch for a minor fix and it kicked off in Appveyor as expected, so this may well be due to the previous two PRs coming from cloned repos. Might need to dig further into this...

**Comment by kal** [comment]
Recent PRs have worked fine so I'm going to close this.
