### ISSUE TITLE
User Guide and Developer guide links broken -- 404 Page not found

### ISSUE THREAD

**Issue by charbull** [dotnetrdf/dotnetrdf#116]
Hello, 

Minor issue, the pages of User Guide and Developer guide are broken in the main readme.md
https://github.com/dotnetrdf/dotnetrdf

http://www.dotnetrdf.org/content.asp?pageID=User%20Guide

They are working well in the Wiki section.

an update will be nice :)
Charbel

**Comment by tpluscode** [comment]
Thanks for pointing this out. I guess some of the old pages have been removed. I fixed some link and I'm closing this issue for now but we need a more thorough readme overhaul
