### ISSUE TITLE
Tools page in wiki needs updating

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#119]
See https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Tools

- [x] Link to download is invalid. We should probably add a release to the tools repo and link to that rather than to Codeplex.
- [x] Cross-reference links need fixing.

Important to get this done as it is linked to from the website.

**Comment by tpluscode** [comment]
We could also start publishing to Chocolatey and add a link to that. Appveyor is almost set up but we still need to create a package (dotnetrdf/dotNetRDF.Toolkit#1).

**Comment by kal** [comment]
Page is updated with the basic links for now. Chocolatey links should be added when we get the package sorted out.
