### ISSUE TITLE
Objects not available in .NET Standard 2.0.

### ISSUE THREAD

**Issue by daviddunson** [dotnetrdf/dotnetrdf#135]
I am upgrading my projects to .NET Standard 2.0 and noticed that dotNetRDF also supports .NET Standard 2.0; however, I am unable to create a new Graph or other basic objects. The code below will compile with a *net40* target framework, but not *netstandard2.0*. The compiler says "Not Available".

```
        public Class1()
        {
            var graph = new VDS.RDF.Graph();
        }
```

Here is the project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net40;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotNetRDF" Version="2.0.0-pre0009" />
  </ItemGroup>

</Project>
```

**Comment by kal** [comment]
It looks like the .NET Standard 2.0 build is broken (not actually including any source files in the build). I'm working on a fix for this...

**Comment by kal** [comment]
If you update to 2.0.0-pre0010 your code should compile now!

**Comment by daviddunson** [comment]
That it did. Thank you for such a quick response.
