### ISSUE TITLE
memory or memory addressing issues

### ISSUE THREAD

**Issue by saschakunz** [dotnetrdf/dotnetrdf#155]
Hi,

I am trying to store roundabout 80million triples. I started with much less so I am not using the Handlers API. Instead now I am trying to "fix" (is a feasibility thing, not for productive work) that by writing the triples to a file / triple store and clear the graph afterwards event based (after added n triples) by doing this:
graph.Clear();
graph.Dispose();
UriFactory.Clear(); 

My problem now is that I am receiving an out of memory exception which means in my case I suppose that addressing the memory on a 32bit machine is not working anymore (not at the moment I took the screenshots).
Most of the memory is being freed but there is still a big part left that is not being cleared. Due to that I compared memory snapshots between the lines above and found out that there is an object type "VDS.Common.Trees.AVLTree<VDS.RDF.Triple, Object>" that persists in terms of the number of objects before graph.Clear() and also after line UriFactory.Clear(). On the following screenshots there is my comparison of the before and after memory snapshots and as you can see the count stays at 449,922.

![memory snapshots](https://user-images.githubusercontent.com/9549185/34218250-fba114f4-e5ad-11e7-9e55-ff18d3b3d159.png)

I am using a NonIndexedGraph and as recommended to save memory the following Options are set:

Options.FullTripleIndexing = false;
Options.InternUris = false;

Did I forget something or is there something or is there a way to reduce the number of these AVLTree objects as well?

Thank you very much for your help
Sascha

**Comment by kal** [comment]
Thanks to @rvesse it looks like we should have a fix for this. We can roll this into the 2.1 release

**Comment by kal** [comment]
Updated dependencies in the 2.1 release. Hopefully this memory usage issue will be fixed now.
