### ISSUE TITLE
dotNetRDF 0.0

### ISSUE THREAD

**Issue by langsamu** [dotnetrdf/dotnetrdf#159]
The assembly name for the 2.0 dll from [NuGet](https://www.nuget.org/packages/dotNetRDF/2.0.0) is `dotNetRDF, Version=0.0.0.0, Culture=neutral, PublicKeyToken=6055ffe4c97cc780`.

**Comment by kal** [comment]
It looks like GitVersion didn't add the necessary assembly info property - it only updates existing properties so we need to add some dummy value to the existing assemblyinfo files. While in there it would make sense to update the copyright year as well.

**Comment by kal** [comment]
@langsamu - is this a breaking issue for you or just an annoyance? Just to help me decide if I should push 2.0.1 to fix this and #158 alone or if it can wait until I get chance to look at #140 and #141

**Comment by langsamu** [comment]
Not a breaking issue at all. Was just weird in my project file. Made me think I did something wrong during package update.
