### ISSUE TITLE
Creating node of unknown type from string

### ISSUE THREAD

**Issue by passingthru** [dotnetrdf/dotnetrdf#167]
How can I create node from string without knowing if its literal or URI? Since the methods for loading triples from file can determine it automatically, is there a NodeFactory or other method for this also?

**Comment by kal** [comment]
There are factory methods on Graph for doing this as described in the [Library Overview](https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Library-Overview). You would need to test if the string you have is a URI or not, and decide then if you want to construct a LiteralNode or a UriNode (we don't do this for you as there are valid use cases for creating a LiteralNode whose value is a URI).

**Comment by passingthru** [comment]
I assume this also means manually testing literal string for language or datatype and deciding which type of literal node will be created? I am already doing this, just wasnt sure if this is the right way. Thank you for explanation.

**Comment by kal** [comment]
@passingthru - yes you will. Depending on the syntax of the string you are parsing there may be some helpers buried in the dotNetRDF library.
