### ISSUE TITLE
OWL 2 RDF/XML file to an XML file

### ISSUE THREAD

**Issue by edson900** [dotnetrdf/dotnetrdf#176]
Is it possible to convert a  OWL 2 RDF/XML file to an XML file using the dotNetRDF tool?

Is Yes, Can you please send me the steps to accomplish it.

**Comment by kal** [comment]
I'm not quite sure what you are asking for here. RDF/XML *is* XML. Is there some sort of specific conversion you are looking to perform?

**Comment by edson900** [comment]
Listed below is the original format and I need to have this file transformed to the format in the second file which is stripped of the rdf tags.

[pizza_rdf_example.txt](https://github.com/dotnetrdf/dotnetrdf/files/1841623/pizza_rdf_example.txt)


[datasource2.txt](https://github.com/dotnetrdf/dotnetrdf/files/1841666/datasource2.txt)

**Comment by tpluscode** [comment]
Transforming a RDF/XML (or OWL all the same) is tricky business if you attempt with XML tools. It is not nearly enough to `strip the rdf tags`, because those formats can express same data in multiple ways (such as using attributes and child nodes interchangeably).

I think that your simplest solution would be to load the file into a `Graph`, query it for the required data and export the XML manually.

**Comment by edson900** [comment]
I am using Protégé 5.2.0  where I select a URI.  How can I load that into a graph, query it and export the XML?

**Comment by edson900** [comment]
I need a working example in dotnetrdf with the steps to convert the pizza_rdf_example.txt (RDF) file to the datasource2.txt (XML) format as listed above. 
Please also me send me names of the experts I can contact to make this transformation.
Thank You

**Comment by christopheralcock** [comment]
having a brief look at the files, as far as i can see:
pizza_rdf_example.txt is an ontology
datasource2.txt is instance data
there is no way to convert between them, with any tool, they are saying different things.
datasource2.txt is talking about individual items in a database (of planets)
pizza_rdf_example.txt is talking about classes (of pizza) that items can belong to

what are you actually trying to do? create a table of pizzas?

**Comment by edson900** [comment]
I need the output to be Lowered to XML without the OWL/RDF syntax.

**Comment by kal** [comment]
I think this might make a better question on StackOverflow. I'm still not quite sure what the expected output is but it doesn't seem to me to be a bug with dotNetRDF.
