### ISSUE TITLE
Email address taken as UriNode

### ISSUE THREAD

**Issue by gabrieldelaparra** [dotnetrdf/dotnetrdf#179]
Not sure if this is a normal/expected behaviour, but emails are taken as UriNodes. 
I think that they should be not. (?)

**Comment by tpluscode** [comment]
Hi. Thank you for reporting. Please tell us which version you're using and share some code snippet to try

**Comment by rvesse** [comment]
Anything that meets the generic URI syntax can be accepted, I would guess you have a `mailto:foo@bar` type URI which is valid according to the relevant RFCs and thus acceptable as a `UriNode`

**Comment by kal** [comment]
Hi @gabrieldelaparra . I agree with @rvesse - you are probably seeing the default processing of a mailto: URI. I'm closing this ticket, but if this is not the case please respond to reopen.
