### ISSUE TITLE
Use dotnetrdf org to publish nuget packages

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#187]
There is an existing dotnetrdf organisation on the NuGet site and it would be good to use this org as the owner for our NuGet packages. However, I'm not a member of this org and I can't find a way to see who is.

@rvesse  - did you set this up? If so can you add me as a member of the organisation please?

**Comment by rvesse** [comment]
@kal Sorry just returning from paternity leave, I have transformed the old `dotnetrdf` user account on NuGet into an organisation and added you as an administrator

Please close this out once you have accepted that membership and verified you have access to administer the organisation
