### ISSUE TITLE
Lingering Graph.Triples.XXXNodes

### ISSUE THREAD

**Issue by langsamu** [dotnetrdf/dotnetrdf#188]
When triples are removed from a graph, the nodes from those triples still show up from the three convenience properties on `BaseTripleCollection` (`SubjectNodes`, `PredicateNodes` and `ObjectNodes`).

`NonIndexedGraph`s behave as expected (no lingering nodes), so I'm guessing this is related to https://github.com/dotnetrdf/vds-common/pull/9 (memory usage when removing from `MultiDictionary`).

```c#
var indexed = new Graph();
indexed.LoadFromString("_:s <urn:p> _:o.");

var nonIndexed = new NonIndexedGraph();
nonIndexed.LoadFromString("_:s <urn:p> _:o.");

Assert.Equal(nonIndexed, indexed); // Yes

indexed.Clear();
nonIndexed.Clear();

Assert.Equal(nonIndexed, indexed); // Yes

Assert.Empty(nonIndexed.Triples); // Yes
Assert.Empty(indexed.Triples); // Yes

Assert.Empty(nonIndexed.Triples.SubjectNodes); // Yes
Assert.Empty(nonIndexed.Triples.PredicateNodes); // Yes
Assert.Empty(nonIndexed.Triples.ObjectNodes); // Yes

Assert.Empty(indexed.Triples.SubjectNodes); // No
Assert.Empty(indexed.Triples.PredicateNodes); // No
Assert.Empty(indexed.Triples.ObjectNodes); // No
```

**Comment by kal** [comment]
The fix in VDS.Common almost does the trick, but because the retraction of a triple can leave a multi-dictionary list empty there needs to be some guard code in the TreeIndexedTripleCollection to detect this case and remove the list from the MultiDictionary.

Fixed now in master.
