### ISSUE TITLE
HtmlWriter breaks on retraction

### ISSUE THREAD

**Issue by langsamu** [dotnetrdf/dotnetrdf#189]
h/t @christopheralcock 

When triples are removed from a graph prior to saving it with an `HtmlWriter`, the generated HTML is broken, with extra `tr`s for retracted statements and `td rowspan="0"` for removed subject nodes.

This is becuase [HtmlWriter relies](https://github.com/dotnetrdf/dotnetrdf/blob/350fb42236d1c048a6503712043dd76e80d7d247/Libraries/dotNetRDF/Writing/HtmlWriter.cs#L190) on `BaseTripleCollection.SubjectNodes`, which is broken for indexed graphs (#188).

![screenshot](https://user-images.githubusercontent.com/240741/39947449-e00d25da-5569-11e8-8bcf-1881ba04a1d3.png)

**Comment by kal** [comment]
The fix for #188 also fixes this issue. I've added the repro you provided and confirmed that this is the case.
