### ISSUE TITLE
When will a NuGet package for 2.1 be released?

### ISSUE THREAD

**Issue by faubulous** [dotnetrdf/dotnetrdf#191]
Hi folks,

we're planning for an upcoming release of our RDF ORM mapping library 'Semiodesk Trinity'. For this new release we are relying on the SparqlQueryGenerator changes in the current master branch which have been merged recently. I'm just curious when a NuGet package for the 2.1 release will be available?

**Comment by kal** [comment]
Hi,

There is now a 2.1 pre1 on NuGet. Can you please give it a try and let me know if there are any problems. There shouldn't be but just in case :-)

If everything is fine, then I will retag master with a 2.1 release tag.

Cheers

Kal

**Comment by faubulous** [comment]
Dear Kal,

thanks for taking care so quickly. I'll give the package a try tomorrow.

**Comment by faubulous** [comment]
Dear Kal,

sorry for not getting back to you immediately. We have tested the NuGet package for a while now and have not encountered any issues.
