### ISSUE TITLE
How to add triple to graph

### ISSUE THREAD

**Issue by RammG** [dotnetrdf/dotnetrdf#194]
I have a graph initialed from a rdf file, and use GetTripleWithSubject() to get triple's list with one subject. How I can construct another graph with this triples result?

**Comment by tpluscode** [comment]
The manual way is to create a new `Graph` add the triples to it.

Or, you can use a `CONSTRUCT` SPARQL Query, for example using [`QueryBuilder`](https://bitbucket.org/romanticweb/dotnetrdf/wiki/Examples/Construct).
