### ISSUE TITLE
Some Wiki links are broken

### ISSUE THREAD

**Issue by CXuesong** [dotnetrdf/dotnetrdf#198]
For example, there are red links on https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Configuration-HTTP-Handlers . While the (intended) link targets actually exists, the links need to be fixed.

**Comment by CXuesong** [comment]
Plus, the following example code snippet provided on https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Configuration-HTTP-Handlers
```ttl
@prefix <http://www.dotnetrdf.org/configuration#> .

<dotnetrdf:/folder/endpoint> a dnr:HttpHandler ;
  dnr:type "VDS.RDF.Web.QueryHandler" .
```
seems should be
```ttl
@prefix dnr:<http://www.dotnetrdf.org/configuration#> .

<dotnetrdf:/folder/endpoint> a dnr:HttpHandler ;
  dnr:type "VDS.RDF.Web.QueryHandler" .
```

**Comment by kal** [comment]
These documentation issues are now fixed in the wiki
