### ISSUE TITLE
Repository restructuring

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#2]
The main idea with this proposal is to make it easier to work with the source code repo by moving some of the "subprojects" into their own repository. I think it might make sense to do this in stages, start with the really obvious things that can be easily split out from the main repo and then work with that for a bit and see if it makes sense to further split the main repo or the other repos. So I would propose that we end up with the following repos:
- dotnetrdf - the core libraries and all of their related tests (this is Libraries/core and Testing in the original repo)
- samples - sample applications; the contents of the Samples directory in the original repo
- utilities - the rdf tools such as the editor, sparql gui and so on; the contents of the Utilities directory in the original repo plus the editor and editor.wpf projects from the Libraries directory in the original repo.
- virtuoso - the Virtuoso data library
- fulltext - the fulltext indexing library
- spin - the SPIN library

Where references between the different repos is necessary, this can be done using Git submodules.

See also #3

**Comment by tpluscode** [comment]
I agree. I'd do git filter-branch on subprojects to retain some commit history

I'm not sure I'd go for submodules though. Why not simply depend on core libs from NuGet?

**Comment by kal** [comment]
The reason for using submodules is that it would be easier to debug issues where the problem crosses library boundaries. Perhaps not necessary for samples and utilities, but I expect it would be useful for virtuoso, fulltext and sping. We could always choose on a case-by-case basis.

**Comment by tpluscode** [comment]
Other than that I'd like to simplify the solution and build structure: 

* simplify targeting multiple frameworks (should be possible with only one csproj for each lib)
  this will simplify packaging too
* simplify versioning (see [GitVersion](https://gitversion.readthedocs.io/en/latest/))
* Get rid of NAnt maybe?

**Comment by kal** [comment]
Targeting: Ideally I would like us to move to .NET Core on the 2.0 branch. I think on 1.x I'm happy to stick with the current mishmash of solutions (or at least not so upset by it that I want to spend time messing around with .proj files...) <sup>1</sup>

Versioning: I'm not 100% sold on the GitVersion approach, but I'm open to being convinced of its value!

NAnt: I would like to get rid of this too. Again though I'm not too worried about spending time on this on the 1.x branch <sup>1</sup>

I would also like a build process that "just works" on non-Windows platforms for everything except the UI tools.

<sup>1</sup> Assuming that we move to the position of doing active development on 2.0

**Comment by tpluscode** [comment]
I agree that we should do any of this only for 1.9+. .NET Core sounds ambitious though :)

Regarding GitVersion, it is tricky to get just right, but it's rock solid on the tooling side. It just works.

**Comment by tpluscode** [comment]
Regarding submodules, with moving the library projects to project.json, this won't be an option unless we move everything to the new format. I expect that to be harder with the installer project. Personally I'd leave the as they are, move to a new repository and fetch lib dependencies from NuGet. It could be from a CI feed if we wanted to move faster
