### ISSUE TITLE
UriParser example doesn't work

### ISSUE THREAD

**Issue by haga2112** [dotnetrdf/dotnetrdf#206]
On the Basic Tutorial, section **Reading RDF** the **_UriLoader_** example doesn't work:

```
IGraph g = new Graph();
UriLoader.Load(g, new Uri("http://dbpedia.org/resource/Barack_Obama"));
```

Although the dbpedia page about Barack Obama is working when loading it I get the following exception:

**System.OperationCanceledException: 'The operation was canceled.'**

**Comment by kal** [comment]
I suspect that this may have been a problem with the dbpedia endpoint. I have tried the code out in a simple console app this morning and it behaves as expected.
