### ISSUE TITLE
Building SPARQL with VALUES clause

### ISSUE THREAD

**Issue by Annhiluc** [dotnetrdf/dotnetrdf#211]
On the Basic Tutorial section **UserGuide Building SPARQL**, there is no indication of how to create a VALUES clause within a SPARQL. For example, 

`SELECT ?x
 WHERE { VALUES (?x) { (http://www.w3.org/2001/vcard-rdf/3.0#FN) } }`

How can I create a SPARQL with a VALUES clause using the `QueryBuilder`?

**Comment by tpluscode** [comment]
Hi @Annhiluc. Indeed `VALUES` is not currently possible with the query builder. Let me start working on that!

**Comment by tpluscode** [comment]
Just a question first @Annhiluc, @kal, @rvesse 

The topmost `VALUES` can be placed both inside and outside a query

```
SELECT ?x
{
  VALUES ?x ( 5 )
}
```

```
SELECT ?x
{
}
VALUES ?x ( 5 )
```

Are such two queries always equivalent? If so, then the builder can be made simpler and only ever generate one form.

**Comment by Annhiluc** [comment]
For my purposes they will always be inside the query, but I can't speak for equivalency. Thanks @tpluscode!

**Comment by rvesse** [comment]
@tpluscode For a trivial query like the example they are equivalent.  For anything non-trivial they are  not guaranteed to be equivalent because a top level `VALUES` applies after aggregations and projections.

**Comment by tpluscode** [comment]
@Annhiluc I finally arrived at a draft implementation for `VALUES`. Here's my current idea, which does not explore all possibilities for this functionality

```c#
var select = QueryBuilder.SelectAll().GetQueryBuilder();

// variables declared once, followed by per-tuple calls.
// values must match order of variables, as in actual SPARQL
// null becomes UNDEF
select.InlineData("name", "age", "uri")
   .Values("John", 35, new Uri("http://john.doe"))
   .Values("Jane", 28, null);

// Values is a dead end, need to hold on to reference to the query builder
select.where(/* ... */)
var query = select.BuildQuery();
```

Now, there are a number of design choices to make:

1. How to pass in typed/tagged literals?

    I was thinking of anonymous types like `Values(new { literal = "Tomasz", language = "pl"})` but 
    such approach would not get IDE feedback which will be awkward.

    Another option is to expand the API with yet another layer like a value builder

    ```c#
    Value(vb => vb.Variable("o").Value("Tomasz", "pl"))
    ```

    This way the API is more verbose but self-explanatory. Of course it would co-exists with the shorthand presented above.

1. How to append `VALUES` outside of the query

    My best idea is an additional method on the builder, which would have no effect if used on a nested graph pattern

    ```c#
    queryBuilder.Values("first", "last").Outside().Values(/* ... */)
    ````

    Naming is awkward though. `Outside`? 🤢

**Comment by tpluscode** [comment]
Any input welcome @Annhiluc @rvesse @kal 🙂

**Comment by rvesse** [comment]
For part 2 I prefer the second option

**Comment by tpluscode** [comment]
Thanks @rvesse 

Thanks @kal. Yes, overload of `Values`. And I thought that `UNDEF` would be simply passed as `Value(null)` but on a builder a dedicated method does indeed seem more elegant 👍. Then again, one does not contradict the other.

**Comment by Annhiluc** [comment]
Yes, I agree with @rvesse and @kal on both parts. Thanks for this!
