### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#223]
@kal since 2.1 we've closed PRs #203, #205, #208, #209 and #214 

I see that there is a version 2.2 planned in milestone but what would you say about pushing those minor improvements as 2.1.1?

**Comment by kal** [comment]
Actually I think push these as 2.2 seeing as the changes are a bit more than just patches. We can easily and rename the existing 2.2 milestone to 2.3

**Comment by tpluscode** [comment]
Good point. I moved currently closed issues from 2.3 to a new 2.2 milestone and added the above
