### ISSUE TITLE
Any class to parse update SPARQL?

### ISSUE THREAD

**Issue by WangGangCH** [dotnetrdf/dotnetrdf#231]
I'd like to parse update SPARQL with RDF parser, however it throw exceptions:
`Unexpected Token encountered - expected a BASE/PREFIX directive or a Query Keyword to start a Query`

My SPARQL is like:
```
PREFIX ext: <http://example.com/ext/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX text: <http://jena.apache.org/text#>

DELETE {?s ext:name ?n}
INSERT {?s ext:name "Hey !"}
WHERE {
VALUES (?s) { (Hey-Id) }
}
```

is there any class or method to parse them correctly?

**Comment by christopheralcock** [comment]
you're using the prefix "ext:" without defining it
you need to add a line to the top like

`PREFIX ext: <http://example.com>`

**Comment by WangGangCH** [comment]
apology, I added this line actually, forget to past here. @christopheralcock

**Comment by WangGangCH** [comment]
and here is the code I used to parse:
```
var parser = new VDS.RDF.Parsing.SparqlQueryParser();
var query = parser.ParseFromString(queryString);
```

**Comment by tpluscode** [comment]
You should be using `SparqlUpdateParser`

**Comment by WangGangCH** [comment]
Great, thanks @tpluscode
