### ISSUE TITLE
Change FileMode of JsonLdWriter to be consistent with other writers

### ISSUE THREAD

**Issue by bergdahl** [dotnetrdf/dotnetrdf#232]
I noticed that the file handling in Save() of the writers are inconsistent. As an example, 
JsonLdWriter uses FileMode.CreateNew (which fails if the file exists) while RdfXmlWriter along with all the other I looked at uses FileMode.Create (which overwrites any existing files).

Is there a functional reason for this?

**Comment by kal** [comment]
@bergdahl - nope I don't think there is any reason why it should be different except that I happen to think that FileMode.CreateNew is a better developer experience than FileMode.Create! But that said, inconsistency is even worse than silent over-writing of files so we should change this.
