### ISSUE TITLE
Suspiciously short time of executing a query

### ISSUE THREAD

**Issue by EvkaS** [dotnetrdf/dotnetrdf#244]
Executing the `SparqlQuery` using `RemoteQueryProcessor.ProcessQuery(SparqlQuery query, GraphCallback rdfCallback, SparqlResultsCallback resultsCallback, Object state)` for the first time takes around 80 milliseconds, the second execution lasts 0.3 milliseconds according to `SparqlQuery.QueryExecutionTime` property. Can both of these values be correct?

Supposing the parameters are correct:
```
SparqlQueryParser parser = new SparqlQueryParser();
SparqlQuery query = parser.ParseFromString(queryString);
SparqlRemoteEndpoint endpoint = new SparqlRemoteEndpoint(new Uri (endpointUriString));
ISparqlQueryProcessor processor = new RemoteQueryProcessor(endpoint);
processor.ProcessQuery(query, myRdfCallback, myResultsCallback, myState);
var time = query.QueryExecutionTime;
```

**Comment by kal** [comment]
Hi @EvkaS,

The `SparqlRemoteEndpoint` just makes and HTTP call to the endpoint. My guess is that the server you are connecting to has cached the results and is returning the result from the cache or that some intermediate proxy server has cached the result for you.

I think if you are seeing the same results both times then this is the most probably explanation. If you are seeing inconsistent results on the second call, please feel free to reopen this issue with some additional information about what the results are the first and second time, the type of endpoint that you are connecting to and the query you are sending.

Cheers

Kal
