### ISSUE TITLE
MIMETypes Helper specifies application/json for RDF/JSON

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#250]
When taking a look at #249, I notice that in MIMETypesHelper we currently define "application/json" and "text/json" as possible media types for RDF/JSON. 

As RDF/JSON is deprecated as a JSON format for RDF in favour of JSON-LD I wonder if we should consider removing these media types (or moving them to the list of media types for JSON-LD)

**Comment by tpluscode** [comment]
I don't think they really hurt anyone, do they? Maybe there is someone out there using them...

But I don't think we should conflate their media types with JSON-LD. It has it's own proper `application/ld+json`. Mixing that with the generic JSON ones would not be correct IMO

**Comment by kal** [comment]
My only concern is that when retrieving from an endpoint if the Content-Type header comes back as application/json we are going to run it through the RDF/JSON parser rather than through the JSON-LD parser. As you say, there are proper media types for both RDF/JSON and JSON-LD so arguably this shouldn't happen - I guess its just a question of what's the best thing to do when it does :-)

However, I'm happy to leave it as is for the moment, and let's see if anyone hits it as an issue as JSON-LD picks up more traction.
