### ISSUE TITLE
Remove netcore 1.0 target

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#256]
Hi all,

I just want to get a bit of feedback on this. Now that .NET Core 1.0 has been end of lifed (https://devblogs.microsoft.com/dotnet/net-core-1-0-and-1-1-will-reach-end-of-life-on-june-27-2019/), I think it makes sense to remove support from dotNetRDF for two reasons. 

1) Folks on .NET Core 1.0/1.1 are being strongly encouraged to migrate to .NET Core 2.1/2.2 - so we can add our own bit of pressure there :-)

2) It's one less target to support and its one that has a lot of idiosyncracies and missing features because of the restricted API set of .NETStandard1.x, so this makes our build smaller, tidier and more consistent across the platforms that we do support.

Does anyone have anything to say in defence of .NET Core 1.0 support?

@langsamu, @tpluscode, @rvesse

**Comment by tpluscode** [comment]
:+1: from me.

Do you intend to also drop `netstandard1.x`?

**Comment by langsamu** [comment]
Nothing in defence and very much in favour of dropping it.

Specifically I know this will not affect @ukparliament (the only dotNetRDF user I know).

**Comment by kal** [comment]
Thanks guys. @tpluscode - yes will drop netstandard1.x support from the library and move to just .NET Framework and NETStandard2.x.

**Comment by rvesse** [comment]
@kal I haven't used .Net in so long that I don't even know what all these targets are anymore so no I don't have any opinions either way
