### ISSUE TITLE
Namespace in rdf:resource is replaced by prefix &prefix; ??

### ISSUE THREAD

**Issue by githubX82jKm** [dotnetrdf/dotnetrdf#257]
Please have a look at the attached sample.
Code in sample.cs results in test.xml.

I am wondering if it is correct to replace namespace in attribute value? And why it is then masked by &; ??

**http://iec.ch/TC57/2013/CIM-schema-cim16#test**

is replaced by

**&cim;test**

If it is correct: how can I avoid replacing the url by namespace prefix for this object only?

[sample.zip](https://github.com/dotnetrdf/dotnetrdf/files/3345561/sample.zip)

Thanks. Regards,
Julius

**Comment by langsamu** [comment]
You can tell RdfXmlWriter [not to use a DTD](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Writing/RdfXmlWriter.cs#L76-L85) in the generated output, then it won't write XML entity references for IRIs:
```cs
// using VDS.RDF.Writing;
var writer = new RdfXmlWriter { UseDtd = false };
```

You can also control this globally:
```cs
// using VDS.RDF;
Options.UseDtd = false;
```

BTW entity references are perfectly legal, but in my opinion the default should be not to use DTD for writing RDF/XML, as developers are mostly unfamiliar with it and it could cause problems when parsing XML naively.

**Comment by githubX82jKm** [comment]
Thank you for the quick response!
