### ISSUE TITLE
newtonsoft.json reference set to 11.0?

### ISSUE THREAD

**Issue by reeset** [dotnetrdf/dotnetrdf#261]
I'm not sure if this is in the dotnetrdf component or one of it's dependencies -- but when I build a project that references both dotnetrdf and newtonsoft -- I get the following error:

------ Starting pre-build validation for project 'MarcEdit_Setup64bit_User' ------ 
WARNING: Unable to find dependency 'NEWTONSOFT.JSON' (Signature='30AD4FE6B2A6AEED' Version='11.0.0.0') of assembly 'dotNetRDF.DLL'

I was under the impression that dotnetrdf could use the most current version of the newtonsoft.json assembly -- but this isn't my experience.  I find when using the component to query a sparql endpoint, I cannot using the json parsing.  

I've forked the project to try updating the references to try and figure out where this is coming from.

**Comment by reeset** [comment]
So rebuilding after updating specific dependencies removed the dependency error when I build and seems to correct when I've seen json results fail.  It seems to be primarily when I use this construction:
VDS.RDF.Writing.SparqlJsonWriter jwriter = new VDS.RDF.Writing.SparqlJsonWriter();
jwriter.Save(results, _localtmp);
_innerText = System.IO.File.ReadAllText(_localtmp);

It fails silently here and gives empty results (when other formats like xml work).  If I change the request so that I'm making an HTTPWebRequest directly and setting the Accepted return format to application/sparql-result+json I get the results that I would expect.

**Comment by tpluscode** [comment]
Correct, dotNetRDF is built with Newtonsoft 11.0.2: https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/dotNetRDF.csproj#L61

I expect it would work with the later versions but .NET is notoriously picky with referenced assembly versions. Usually those would be runtime errors though. I never encountered this `pre-build validation` error.

The first thing I try is to add an assembly redirect to whatever version you have locally. Have you tried that?

**Comment by reeset** [comment]
Ack -- no, I hadn't.  That would definitely be easier.  I'll give that a try and see if it takes care of the problem.  

--tr

**Comment by reeset** [comment]
Adding the redirect for both newtonsoft and the HtmlAgilityPack (which I'd been keeping at 1.8.x) worked.
