### ISSUE TITLE
The union relationship was incorrectly parsed

### ISSUE THREAD

**Issue by MrJiang724** [dotnetrdf/dotnetrdf#264]
We have a SPARQL query. It has the wrong child pattern construction.

Here is the SPARQL query:
```
PREFIX rel: <http://www.w3.org/relation/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT DISTINCT ?x
WHERE
{
	{ 
		{ 
(1)                {?x rel:actor_of_film ?person.} 
                    UNION 
(2)                {?x rel:director_of_film ?person.} 
                    UNION 
(3)                {?x rel:producer_of_film ?person.} 
                    UNION 
(4)                {?x rel:writer_of_film ?person.} 
		} 
(5)    ?x rel:film_type "love film". 
(6)    ?x rel:release_date_of_film ?release_date. 
(7)    FILTER (?release_date < "2017-04-07T00:00:00Z"^^xsd:dateTime) 
        {
(8)       ?x rel:product_company_of_film ?film_company.
        } 
        UNION 
        {
(9)        ?film_company rel:child_companys ?child_company. 
(10)      ?x rel:product_company_of_film ?child_company
        } 
(11)  ?x rel:film_type "love film". 
(12)  ?x rel:release_date_of_film ?release_date. 
(13)  ?x rel:score_of_film ?score. 
	} 
(14)  VALUES (?film_company){("Paramount Pictures")}
(15)  VALUES (?person){("Tom hanks")}
}
ORDER BY DESC(?score)
```

I try to use following code to parse the sparql query.
`
var sparql = new VDS.RDF.Parsing.SparqlQueryParser().ParseFromString(query);
`

**Comment by kal** [comment]
Hi,

Can you tell me a bit more about this problem. How does the error manifest itself? Do you see an error from the parser or does it produce an incorrect algebra for the query?

Any details you can add and/or simplified examples will help me in tracking down the problem.

Thanks!

Kal

**Comment by MrJiang724** [comment]
Sorry for not describing the problem clearly. The parser don't throw exception. It returned a SPARQLQuery object, but there are some mismatch with expected result. I numbered each triples.
Actual RootGraphPattern:
![image](https://user-images.githubusercontent.com/10070264/64410357-71506000-d0bd-11e9-85ff-9780c38969a4.png)

Expect RootGraphPattern:
![image](https://user-images.githubusercontent.com/10070264/64410339-672e6180-d0bd-11e9-91f5-813bc9bdb17e.png)

I use .Net Framework 4.6 to reference dotnetrdf version 2.2.
You can also use SparqlQueryParser to check it. I think it is easy to reproduce.

**Comment by kal** [comment]
I found the problem in the SparqlQueryParser and applied a fix. Thanks @MrJiang724  for the detailed error report, it was really helpful in finding and squasing this bug!
