### ISSUE TITLE
Connecting to Parlaiment

### ISSUE THREAD

**Issue by zorgoz** [dotnetrdf/dotnetrdf#269]
I am trying to query a Parliament (https://github.com/SemWebCentral/parliament) instance. `QueryWithResultGraph` throws `RdfParserSelectionException` with message: _The Library does not contain any Parsers for RDF Graphs in any of the following MIME Types: application/sparql-results+xml_

**Comment by kal** [comment]
The error message indicates that the result you are getting back is a SPARQL results table and not a graph, that means that your query is a SELECT query rather than a CONSTRUCT query. For this you should instead use the method `QueryWithResultSet`.

**Comment by zorgoz** [comment]
Thank you.
