### ISSUE TITLE
Support for Reading/Writing to Solid PODs

### ISSUE THREAD

**Issue by moisesja** [dotnetrdf/dotnetrdf#275]
Has the support for https://github.com/solid/specification been considered? Sir Tim Berners-Lee has been all over the news and this decentralization technology is gaining track.

His company, inrupt, is fully supporting JavaScript based clients but I haven't seen much from other tech-stacks.

I'll be happy to contribute but there's so much to these dotnetRDF libraries that I need to learn.

**Comment by kal** [comment]
That would be an interesting thing to consider. Solid is quite a big spec (or collection of specs) and I'm not sure that it would be in scope for this project to consider supporting the full range. However I think it could perhaps be in scope for us to provide support for some of the core elements such as SHACL and maybe also elements of Linked Data Platform.

I think that there is probably a more basic question of where this project would fit in the Solid infrastructure. Would we see dotNetRDF as a library for accessing a Solid Pod as you suggest or could it be a core library for building a Solid server or is it something in between. 

All that said, I do worry that dotNetRDF is quite a big project with a relatively small number of active contributors - and that is definitely something to keep in mind when thinking about extending the coverage of the library. Every new feature added is a new feature that will need maintenance and update as the specs update and as the underlying technology changes. One way to mitigate this might be to start this work as separate projects that take dotNetRDF as a dependency. That might help to spread the load and encourage new contributors in to work on green-field libraries...of course that might then be at the cost of reducing the number of people able to contribute to dotNetRDF itself.
