### ISSUE TITLE
URNs and other IRI schemes are not processed correctly

### ISSUE THREAD

**Issue by jrdouceur** [dotnetrdf/dotnetrdf#282]
JsonLdProcessor.IsAbsoluteIri() incorrectly assumes absolute IRIs must contain "://"

Example of valid IRI that fails:  urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6
This example is from https://w3c.github.io/json-ld-syntax/#iris

**Comment by kal** [comment]
I've made a fix to address this. Note that this does not alter the expansion of the value when it occurs in a property. In that case, the JSON-LD spec specifically says to use the presence of // to determine if you have an absolute IRI (https://w3c.github.io/json-ld-syntax/#compact-iris). However it does allow you to use a URN in other places where an absolute IRI is expected.

**Comment by jrdouceur** [comment]
Well, that was amazingly fast!  Thanks very much.

JD
