### ISSUE TITLE
Adding default result messages for constraints (Shacl)

### ISSUE THREAD

**Issue by o-tim** [dotnetrdf/dotnetrdf#293]
First of all a big praise to @langsamu  for the development of the shacl validator. After first tests it works very well. 

Unfortunately there are no standardized messages for the constraints of the shacls. Although the specification does not require such messages, but they would be a great help for using the validator. 

[The spec says in 3.6.2.7](https://www.w3.org/TR/shacl/#results-message)
> In cases where a constraint does not have any values for sh:message in the shapes graph the SHACL processor may automatically generate other values for sh:resultMessage

Is there already a plan for adding such messages or can you please include this in your roadmap?

**Comment by langsamu** [comment]
I've implemented optional default messages per constraint (if shape doesn't itself have a message) and created several actual messages.

I'd appreciate input regarding helpful default messages, as I'm not an experienced SHACL validator user. Perhaps I could create stubs for all the messages and @o-tim you can write the text itself.

Note that messages could be much more expressive (like [which violation](https://github.com/dotnetrdf/dotnetrdf/pull/294/files#diff-c5ebe4aa23a6bf07f582b4082c192b92R57) in the case of `sh:datatype`), but that would require a bigger change than I'm interested in unless there's a compelling argument.

**Comment by kal** [comment]
PR is looking good to me. I think we can separate out the implementation of the mechanics of reporting a default message (which you have done here) and the definition of a suitable default message for the individual constraints into two separate PRs.

Probably some of the more complex reporting could be handled by overriding the Message property on a case-by-case basis but I would be happy with keeping things simple for now.

**Comment by o-tim** [comment]
The request also looks fine to me. I had implemented it similarly locally myself. I will consider texts for the individual constraints.  

Although the implementation over constant in the classes is clean, but for the future use of the validator it would be very useful to have the value of the constraints available after validation without querying the graph again (I know it is necessary for special use cases anyway). This has the benefit that other users, who do not find the default messages useful or need another language, can easily create their own messages. 

The only question I have is where we can place the value of the constraint in the report, since it does not meet the official specifications. I will take a look at the implementation and look for a solution. Maybe @langsamu  has another idea?

**Comment by langsamu** [comment]
> have the value of the constraints available after validation without querying the graph again

5225ae8 exposes validation report results and their properties (including [`sh:resultMessage`](https://github.com/dotnetrdf/dotnetrdf/pull/294/commits/5225ae8f038b7e36c054bd643abb658ca614e431#diff-7fbdf73c0ee4bbb3a896fab08fd0c3a3R148-R173).

Result messages in the validation report graph now default to those hardcoded into constraint implementations and can be redefined by users using shape messages in the shapes graph. The report and result utility wrapper classes now make it easy to access messages and other result properties:
https://github.com/dotnetrdf/dotnetrdf/blob/5225ae8f038b7e36c054bd643abb658ca614e431/Testing/unittest/Shacl/Examples.cs#L136-L141

Does this answer your question?

> The only question I have is where we can place the value of the constraint in the report, since it does not meet the official specifications.

Can you please clarify?

**Comment by langsamu** [comment]
As @kal suggests, I've removed sample messages from constraints, so PR is mechanics only.
