### ISSUE TITLE
Fork VDS.Common?

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#3]
Should we fork the VDS.Common repo from bitbucket as another repo under the dotnetrdf organisation ?

**Comment by tpluscode** [comment]
Remind me what was Rob's stand on this?

**Comment by kal** [comment]
I've not heard back from Rob yet about this. Its possible it got lost in the earlier discussions mailing list discussions so I've pinged over a private email. I'll update this issue when I hear back.
