### ISSUE TITLE
Suggestion: Allow turning off DTD processing for external entities

### ISSUE THREAD

**Issue by marekobitko** [dotnetrdf/dotnetrdf#308]
RDF file such as
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE testingxxe [
	<!ENTITY % xxe SYSTEM 'http://127.0.0.1/test'>
    %xxe;
]>
```
can be used to demonstrate XXE vulnerability.

The dotNetRDF is setting
`DtdProcessing = DtdProcessing.Parse`
and this may be wanted, but it can also lead to XXE attack.

I don't know what would be the best way to address it - perhaps adding an option on API to switch this off, add some kind of whitelisting (not necessary for me personally) etc. This is just a suggestion, I am not giving any priority, I personally used a simple "fix" for my purposes like the following (simplified).

```
settings.XmlResolver = new DenyingUrlResolver();
   
public class DenyingUrlResolver : XmlUrlResolver
{
	public override object GetEntity(Uri absoluteUri, string role, Type ofObjectToReturn)
	{
		throw new InvalidOperationException("DTD entities resolving is not permitted.");
	}
}

```

**Comment by kal** [comment]
Thanks for the suggestion. I agree that it should be possible to disable XML entity parsing through the API. As you do have a work-around for the time being I will add this as a small item to address in the 3.0 milestone.
