### ISSUE TITLE
Feature: JSON-LD 1.1 support. Is there a roadmap planned?

### ISSUE THREAD

**Issue by tmarkovski** [dotnetrdf/dotnetrdf#311]
First of all, thank you for this amazing work you're doing here. I'm impressed with both the rich feature set and the quality of code, too. I was wondering if you have plans on adding support for JSON LD 1.1 API spec. I was able to run the compaction positive test cases from 1.1 against the current code base and got about 110 succeed and 113 fail - I know 1.1 isn't supported, I was just curious if the test harness would work.
I'm maintaining few repos at the Hyperledger org and we plan on adding support for verifiable claims and linked data signatures that use JSON-LD specs. Most specs use 1.1.
I'm open to helping in any way I can.

**Comment by kal** [comment]
Hi @tmarkovski ,

There's not really a roadmap for this as it depends on when the spec is properly finalized (framing as the JSON-LD 1.1 spec is not yet done (Framing is still in draft, the other two are proposed recommendations but not yet finalized); and also on what capacity I have to work on the current implementation.

**Comment by tmarkovski** [comment]
Thank you for the response @kal, I appreciate your time.

**Comment by kal** [comment]
Hi @tmarkovski,

I've started work on this now and created a separate ticket (#315) so I'm going to close this one. Please feel free to chime in on #315 if there is anything to add!
