### ISSUE TITLE
Framing @set vs @list

### ISSUE THREAD

**Issue by aaron-macdonald-acara** [dotnetrdf/dotnetrdf#312]
We are using dotNetRDF 2.5.1 to frame a flattened JSON-LD query response into a hierarchical format and have found a bug wrt @set and @list specifiers.

To illustrate, with the context snippet below:

{
  "@context": {
    "asn": "http://purl.org/ASN/schema/core/",       
    "children": {
      "@id": "http://purl.org/gem/qualifiers/hasChild",
      "@container": "@set"
    }
   "@type": "asn:StandardDocument"
}

The framed result correctly includes properties named 'children' as in the snippet below:

{
  "id": "http://root-guid",
  "children": [
    {
       "id": "http://child-guid",
    }
   ]
}

However if in the context we interchange @set for @list, the framed result does not correctly name the children property as in the snippet below:

{
  "id": "http://root-guid",
  ...
  "http://purl.org/gem/qualifiers/hasChild": [
    {
       "id": "http://child-guid",
    }
   ]
}

We've only recently upgraded from 2.4.0 as there was a bug in that version whereby we could not specify a second @set property in the context in addition to children, as it was simply omitted in the output. 

We assume there is work in progress in the area of framing an list specifiers?

**Comment by kal** [comment]
Hi,

I'm not sure I understand the issue from the details you give. Is the flattened output changed as well? If not then your frame won't match the source which might be why you aren't seeing the output you expect. 

Can you provide me with a minimal example that shows this problem consisting of the following:

- The flattened JSON-LD you want to frame
- The frame used
- The expected output
- The actual output from dotNetRDF

Please ensure that any relevant remote context is also provided. As noted on #311, work on JSON-LD 1.1 is dependent on the time and resources I have available and also dependent on the finalization of those specifications.

**Comment by set** [comment]
You talked about me

**Comment by kal** [comment]
Hi @aaron-macdonald-acara,

I've started work on this now and created a separate ticket (#315) so I'm going to close this one as I suspect the trouble probably comes from the fact that the current implementation is based on a much older draft of the 1.1 specification. Please feel free to chime in on #315 if there is anything to add!
