### ISSUE TITLE
Update JSON-LD processor

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#315]
JSON-LD 1.1 and the Framing spec are now both at PR status so it is a good time to work on updating our implementation which is based on a much earlier draft of the specification.

There is now a new branch for this work (feature/json-ld-1.1) and on there I've added in the W3C test suite and updated the test framework to run those tests in addition to the old jsonld.org test suite. The current implementation with no changes (well, one minor fix that was a quick thing to do) passes 577 out of 1268 tests. Looking through the spec there are several new keywords that need to be implemented so I expect that a large number of the failures are due to that. 

This is related to issue #311 and #312

**Comment by tmarkovski** [comment]
Slightly unrelated, I just submitted a PR https://github.com/json-ld/json-ld.org/pull/731 to track the progress of this library on the json-ld.org homepage.

**Comment by kal** [comment]
I've just merged changes that update the implementation to the newly published JSON-LD 1.1 specifications. This will be a 2.6 release which I hope to get change to push out this weekend.

**Comment by tmarkovski** [comment]
You're the best, thank you @kal
