### ISSUE TITLE
Allow graph name to be a blank node

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#317]
The current ITriple interface only allows Graph to be a URI. The RDF 1.1 Concepts document has clarified that a graph name can be either a URI *or a blank node*. 

This will mean changing the ITriple interface so that the Graph property is an INode.

We might want to consider adding a "utility" interface ISubjectNode as a superclass sitting between INode, and IUriNode and IBlankNode as a way to make assignment to the Graph property a bit more type-safe. This could also be applied to the Subject and Predicate properties.

**Comment by langsamu** [comment]
Yes to ISubjectNode. I often wished there was something like that.

**Comment by kal** [comment]
Thinking maybe that ISubjectNode is a bad name for something that can be subject or predicate. Perhaps IReferenceNode or IRefNode as it is a reference to a resource rather than a resource in its own right (as a literal is...at least in my mind!)

**Comment by kal** [comment]
The PR referenced above addresses this direct issue. There are some follow-on API issues that need to be addressed for 3.0, but I will create separate tickets for these.
