### ISSUE TITLE
Target .NET 5 only

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#319]
Although its still in preview, it will likely be released well before we are done with 3.0 and it has the advantage of allowing us a single unified code-base. 

From a development perspective, it looks like the framework is supported in VS and VS Code. Not sure if Rider is able to support it yet. Appveyor I *think* has .NET 5 preview available on the Visual Studio 2019 images - its not listed in the main docs, but it is mentioned in the image updates - that should be pretty easy to test out though.

**Comment by tpluscode** [comment]
I'm not exactly in the loop but how does this relate to `netstandard2.0`? 

Isn't that a good candidate for the unified, single-target build? It is supported back to .NET 4.6.1 which should be good enough at this point and .NET Core 1.0 could be safe to deprecate too

**Comment by kal** [comment]
To be honest, I was being a bit provocative :-) A major version release is a good place to make a break with the past and so I decided to propose something radical and see what people think!

I'm still a bit confused about the relationship between .NET Standard and .NET 5. I *think* that the situation is that the .NET Standard library will remain, and so for core dotNetRDF, possibly just targeting some version of .NET Standard makes sense. `netstandard2.0` is currently the best balance between supporting a wide range of current .NET implementations. 

It has been quite painful to try to maintain code that is using old .NET APIs and target old platforms. And there is still quite a lot of what I would consider "legacy" stuff outside of the core library (the Web APIs for example, plus most of the tools).  To make it easier to get new work done, I'd like to migrate or remove as much legacy stuff in the 3.0 release as possible (there are some separate tickets around some of that work already).

So in addition to targetting some version of the .NET Standard library for our core library, I think it is also worth considering what we target for things like the tools and the web server add-ins. I'd love to get to the point where we have some cross-platform tools and we have web server add-ins for modern Kestrel-based servers and doing that with one unified .NET 5 might be easier than .NET Core 3.x for the web stuff and .NET Framework 4.8 for the tools.

So perhaps a better approach would be target .NET Standard for the core library and .NET 5 for everything else?

**Comment by kal** [comment]
@tpluscode - it looks like .NET 5 implements netstandard2.1 and so by extension netstandard2.0, so we could probably get away with just targeting netstandard2.0...no need to add it as a target for the library. We may want to update the build process to run tests on .NET 5 though.

If that makes sense to you I'll go ahead and close this one as a Wont Fix

**Comment by tpluscode** [comment]
:+1:
