### ISSUE TITLE
Diff treats literals with different line endings as not equal

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#324]
I'm reviving my R2RML code a little and natural thing was to update dotNetRDF along other dependencies

Turns out that starting with version 2.3 the difference gives me false negative on a graph I comparison.

Here's an online diff: https://www.diffchecker.com/tD6QMbue

In tests the entire subgraph under the first blank node appears as `AddedMSGs`/`RemovedMSGs`

**Comment by tpluscode** [comment]
I expect that is related to #235?

**Comment by tpluscode** [comment]
Oh wait, this is actually passing on CI (appveyor) but I'm running MacOS. Could be something env-specific about comparing nodes?

**Comment by kal** [comment]
It could be something as simple as that, yes. Just to check, the expected outcome is that the two graphs you linked to in the diff should test as equal. AFAICS the only differences picked up by the text diff are ordering and whitespace, right?

**Comment by tpluscode** [comment]
Yes. Both are the result of turtle serialiser I ran inside debugger.

One graph being the result of the process and the other stored in the repo as embedded resource, for comparison.

The look identical as far as the nodes go. While I expect the order to be irrelevant, why would whitespace matter?

**Comment by kal** [comment]
The whitespace shouldn't matter and neither should the order. I just wanted to double check that you expected the DNR graph diff to report that the graphs are equal before I try to reproduce the error.

**Comment by kal** [comment]
So the graphs test as equal on my machine. Thinking about the whitespace issue. while whitespace between tokens in the TTL file don't make any difference, I wonder if the problem may be something to do with line endings *inside* the multi-line literal for the rr:sqlQuery property? If you convert that to a single-line does the test then pass on the Mac? I'm afraid I don't have access to a Mac to try this out myself.

**Comment by kal** [comment]
Hi @tpluscode - did you get a chance to take a look at this again on the Mac? I'm just wondering if it is worth holding up the 2.6 release for.

**Comment by tpluscode** [comment]
Definitely don't hold the release. I tried debugging but the diff is kinda complicated

**Comment by tpluscode** [comment]
Ah, instead of trying to find the code location to inspect, I simply evaluated the suspect values and it is like you said. The difference it between `\n` and `\r\n`

**Comment by kal** [comment]
@tpluscode - I'm wondering if this should be closed as a won't fix as the diff is behaving correctly in the sense that it has correctly detected that you have different string literals. A preprocessing pass that normalizes line endings would sort out this particular problem, but I feel like that is more properly an application concern and not something that the library should handle. Do you agree?

**Comment by tpluscode** [comment]
I guess that is a reasonable choice. Please, go ahead
