### ISSUE TITLE
URI nodes get double-encoded

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#328]
It appears that #197 introduced a problem where URIs get superfluously percent-encoded and the resulting serialisation is incorrect

The problem lies in the [`NTriplesFormatter#FormatUri`](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Writing/Formatting/NTriplesFormatter.cs#L222-L235) method which calls `Rfc3987Formatter.EscapeUriString` on already fully escaped values.

It's interesting that the commented-out check of `u.IsWellFormedOriginalString()` would actually help.

Example: https://dotnetfiddle.net/53TTew

```c#
// unescaped http://example.com/Person/2/Bob/September, 2010
var uri = new Uri("http://example.com/Person/2/Bob/September%2C%202010");
		
// produces http://example.com/Person/2/Bob/September%252C%202010
new VDS.RDF.Writing.Formatting.NTriplesFormatter().FormatUri(uri));
```

**Comment by tpluscode** [comment]
On the other hand an URI like `https://users.wikibus.org/user/google-oauth2%7CC117957693005245427833` always gets correctly encoded. (`%7C` being a replacement for the pipe `|` character)

**Comment by kal** [comment]
Is the difference something to do with the fact that `,` is a reserved character in the IRI spec and `|` is not?

**Comment by tpluscode** [comment]
Ah, that could be it.

I notice that the encoding runs on `Uri#ToString` which leaves the coma encoded (reserved char) but other encoded characters like pipe or space are returned in their original, unencoded form

Maybe the Implementation should always skip anything that is already percent encoded? Simply forward any `%XY` sequence of characters

**Comment by kal** [comment]
Yeah that would make sense. May need to check for the corner case of a % being in the original URI string - at least to see what `Uri#ToString` does with it.
