### ISSUE TITLE
Performance issue retracting triples from large graph

### ISSUE THREAD

**Issue by blackwork** [dotnetrdf/dotnetrdf#340]
Per default, the TreeIndexedTripleCollection implementation is used to manage a tree index for a graph. There is a performance issue retracting triples from a large graph.

STR:
- create graph and add ~500.000 triples
- select e.g. ~20.000 triples from the graph
- retract the list of triples from the graph

To manage the index, `List<Triple>` is used. In Remove situations, the `Contains(triple)` method if .NET `List` has a poor performance. 
Switch to `HashSet<Triple>` will increase the performance.

**Comment by kal** [comment]
Closing this issue as the fix was merged.
