### ISSUE TITLE
Drop Pellet server support

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#348]
I'm not sure that there is a Pellet server available any longer (@joephayes - do you know different ?). 

The open source fork (https://github.com/Galigator/openllet) doesn't appear to have a service feature, and its not something that we have had any questions about for a while. 

Unless there is a compelling reason to keep it, I think it would be best to remove this code from the 3.0 release - it will still be there in the history if someone wants to step up and maintain it as a separate project.

@langsamu @rvesse @tmarkovski  - any objections?

**Comment by joephayes** [comment]
@kal - I checked and no Pellet server is actively being maintained (other than Stardog itself!)

**Comment by kal** [comment]
Thanks for the quick reply and the info @joephayes !

**Comment by rvesse** [comment]
No objections, it's very much a legacy of the throw everything and the kitchen sink approach that I had at the time

**Comment by tmarkovski** [comment]
I'm cool with that.
