### ISSUE TITLE
Add a fluent API for building queries programmatically

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#35]
_Imported from http://www.dotnetrdf.org/tracker/Issues/IssueDetail.aspx?id=260_

Several users have expressed an interest in a more fluent API for building queries than just parsing a string or building the algebra manually

---

Rob Vesse (Wednesday, January 02, 2013 3:55 PM) #

Putting into Unscheduled until such time Tom indicates he feels this is ready to be part of a release

---

Rob Vesse (Monday, November 11, 2013 2:59 PM) #

Pushed back to 1.9 as will be much easier to do with a rewritten SPARQL implementation

**Comment by kal** [comment]
@tpluscode - you want to take this one ? :-)

**Comment by tpluscode** [comment]
Sure. I was thinking to make this into a separate dll actually.

**Comment by kal** [comment]
That sounds like a good plan. Let me know how you want to proceed - if you want to split development off into a separate repo under dotnetrdf then we can arrange that!

**Comment by tpluscode** [comment]
Separate repo would be good eventually.

For now I'd have to see how the old Fluent API code fits branch 1.9. I assume the target is the 1.9/2.0 version and no new features on 1.0.x?

**Comment by kal** [comment]
I think so. To be honest I still haven't had time to really dig into the state of the 1.9 branch and I would like to do that before making the call about no new features on 1.x

**Comment by tpluscode** [comment]
I actually meant 'no new fluent API' features, but yes.

**Comment by kal** [comment]
This is implemented so I think can be closed.
