### ISSUE TITLE
Group By in empty dataset returns one solution

### ISSUE THREAD

**Issue by giacomociti** [dotnetrdf/dotnetrdf#351]
In the following code snippet:

```C#
var query = "SELECT ?s  (COUNT(?o) AS ?c) WHERE {?s a ?o} GROUP BY ?s";
var m = new InMemoryManager();
var result = (SparqlResultSet)m.Query(query);
Assert.Empty(result.Results);`
```
the assertion fails because there is one result with the variable ?c bound to zero.

I expected no results (I don't know the exact W3C specs about this, but other triplestores return no solutions).

**Comment by kal** [comment]
Thanks for the report @giacomociti. I would expect the same behaviour that you do so will take a look into why a result is getting returned.
