### ISSUE TITLE
Improve perfromance on JSON LD processor on CoreKeywords array lookup

### ISSUE THREAD

**Issue by CFlatWouldbeMinor** [dotnetrdf/dotnetrdf#366]
Working on big Json ld based files  see (Issue #300) I think the load time of huge amount of files could be reduced.
This is not so relevant for smaller amount but in order to steadily improve...
Searching is always done for JSON LD k
![IsKeyword](https://user-images.githubusercontent.com/15439103/109958147-347f1c80-7ce6-11eb-96f1-de1fad5258b6.JPG)
eywords on the static array VDS.RDF.JsonLd.Syntax.JsonLdKeywords.CoreKeywords
using a linear array and with the default operator which is culture aware.
This is mainly called from ExpandIri and consumes up to 25% of the time.
As far as I could find this array is only used for lookup. Why not change this to 
HashSet<string>(StringComparer.OrdinalIgnoreCase). // may be Ordinal? I would have to lookup the json ld spec

**Comment by kal** [comment]
Thanks @CFlatWouldbeMinor - its a quick fix to put in a HashSet to make that lookup faster.
