### ISSUE TITLE
Typo in the code sample in UserGuide Updating With SPARQL

### ISSUE THREAD

**Issue by xloggr** [dotnetrdf/dotnetrdf#375]
I think there's a typo in the [UserGuide Updating With SPARQL](https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Updating-With-SPARQL) wiki page.

In the code sample under [In-Memory Updates](https://github.com/dotnetrdf/dotnetrdf/wiki/UserGuide-Updating-With-SPARQL#in-memory-updates) section
```LeviathanUpdateProcessor processor = new LeviathanUpdateProcessor(store);```
should probably be
```LeviathanUpdateProcessor processor = new LeviathanUpdateProcessor(ds);```

**Comment by kal** [comment]
Yes you are right! I'll get that fixed. Thanks for letting me know!
