### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jiatao99** [dotnetrdf/dotnetrdf#377]
Can you please open up the data structure in IxxxBuilder interface so that the advanced user can write extension methods for the QueryBuilder and related interface? For example:

In `ITriplePatternBuilder`, I propose to expose `IQueryBuilder QueryBuilder { get; }` as well as `IList<ITriplePattern> Patterns {get; }` properties.

Therefore, people can write something like this:

```
public static TriplePatternPredicatePart Continue(this ITriplePatternBuilder buider)
{
        var prev = buider.Patterns[builder.Patterns.Length -1];
        return new TriplePatternPredicatePart(builder, prev.Subject, builde.QueryBuilder.NamespaceMapper);
}
```

Developer can write something like
```
QueryBuilder.All()
        .Subject("x").Predicate("y").Object("z")
        .Continue().Predicate(...)
```

**Comment by kal** [comment]
Thanks for the suggestion @jiatao99 

@tpluscode - what do you think? There are probably several such extension points in the query builder that could be opened up to make it easier to extend it with new functionality. I guess its partly a question of how far to go...would be interested in your thoughts as this is mostly your original contribution!

**Comment by tpluscode** [comment]
Yea. I don't see why not :)

**Comment by kal** [comment]
I realized after my comments on #381 that the problem with exposing these properties over the IxxxBuilder interfaces is that it then changes the user experience with Intellisense completion as these properties will then appear as possible completions - which if they aren't used carefully could possibly end up generating incomplete / invalid SPARQL queries.

One possible way to make the internals accessible for additional extensions would be to put those properties/methods exposed for extension into an IxxxBuilderInternal interface that extends the IxxxBuilder interface. This would keep those properties from appearing in code-completion when just building a query with the fluent API and in extension code you would just have to cast from IxxxBuilder to IxxxBuilderInternal to access those "hidden" properties. 

Does that sound reasonable? Can anyone think of a cleaner way to do it that avoids the cast but still keeps those internal properties hidden from the fluent API?

**Comment by jiatao99** [comment]
I disagree with you regarding open the basic data model. My request is to follow MS .net core design pattern (builder contains the basic data structure and use extension method to extend the feature). 

The `public class QueryBuilder` already open all the property and you can always cast from `IQueryBuilder` and do anything you want. 

In my opinion, the QueryBuilder is help developer write SPARQL query not prevent SPARQL syntax error.  If people does not know how to use the library, he will make invalid query anyway. (for example: `.Subject(new Uri("dbo:albumn")`). 

One way might help solve your concern is in `IxxxBuilder` interface, only contains a `IQueryBuilder QueryBuilder {  get; }`. In this case, you are not open up anything. However, it helps to write the chained extension methods like my example above.

Other examples, I can write something like below to make it more user friendly.

.SubjectUri(string) => call .Subject<INode>(string)
.ObjectUri(string)  => call .Object<INode>(string)

The list can be on and on and this can be easily extended by community.

**Comment by kal** [comment]
I understand your perspective as someone who wants to extend the interface, but my concern is maintaining a query builder that enables developers to easily and intuitively create a valid SPARQL query in code. In this respect, exposing QueryBuilder on the TriplePatternBuilder makes it possible for a developer to think that it is valid to go back "up a level" in the query at the point where they are in a triple pattern - which is potentially confusing and could open up the possibility of creating an invalid query which I think that the average user will find frustrating. 

I agree that your point that a developer can always cast and cause all kinds of problems. My concern is with the 80% of developers who won't do that and who just want a clean and streamlined way to construct a valid SPARQL query.

The changes I have proposed (please look at the code on the branch feature/issue-377 if you have not already) tread the line between allowing you to create the extensions that you want and keeping the core API the shape that I would prefer. As far as I can see its a win-win situation. I hope you agree :-)

I believe your example extension would be coded as:

```c#
public static TriplePatternPredicatePart Continue(this ITriplePatternBuilder buider)
{
        var builderInt = (ITriplePatternBuilderInternal)builder;
        var prev = buiderInt.Patterns[builder.PatternsInt.Length -1];
        return new TriplePatternPredicatePart(builder, prev.Subject, builderInt.NamespaceMapper);
}
```

Please note that I haven't validated this in a compiler, so I may have missed something in the syntax there. However, I hope you can see that your extension method is still possible using the changes that I have proposed with only a single additional line of code.

**Comment by jiatao99** [comment]
Thanks for your clarification. I believe either way is fine.

**Comment by jiatao99** [comment]
just realize the following

1. Constructor of `TriplePatternPredicatePart` is Internal
2. `ITriplePatternBuilderInternal` does NOT expose the `.Patterns` property
3. `ITriplePattern` does NOT expose the `Subject` property
