### ISSUE TITLE
Bug QueryBuilder output

### ISSUE THREAD

**Issue by jiatao99** [dotnetrdf/dotnetrdf#378]
Found a bug with Subject using namespace

```
            var builder = QueryBuilder
               .SelectAll();

            builder.Prefixes.AddNamespace("foaf", new Uri("http://xmlns.com/foaf/0.1/"));
            builder.Prefixes.AddNamespace("dbo", new Uri("http://example.com/#"));

            var uri = new Uri("dbo:The_Beatles");
            var query = builder.Where(p =>
               {
                   p.Subject(uri).Predicate("y").Object("o");
               });

            Console.WriteLine(query.BuildQuery().ToString());
```

Output
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://example.com/#>

SELECT * WHERE
{ <dbo:The_Beatles> ?y ?o . }
```

Also, how to match with default namespace in subject? For example `:The_Beatles`? You can not construct URI using this string.

**Comment by kal** [comment]
To build a triple pattern with a QName subject you need to use the following pattern:

    builder.Subject<IUriNode>("dbo:The_Beatles").Predicate(...).Object(...);

There is a similar override available for Object:

    builder.Subject("x").Predicate("y").Object<IUriNode>("dbo:The_Beatles");

For predicates the method is slightly different:

    builder.Subject("x").PredicateUri("rdfs:label").Object("y");

Hope that helps! If I've missed something please don't hesitate to reopen the issue or submit another issue!
