### ISSUE TITLE
optimization proposal for Service

### ISSUE THREAD

**Issue by giacomociti** [dotnetrdf/dotnetrdf#382]
Hello, I'm experimenting with an optimization based on [this W3C document](https://www.w3.org/TR/2013/REC-sparql11-federated-query-20130321/#values). 
Instead of calling the remote query once for each solution, we can inject all the values at once (or in chunks of limited size).
If this is of any interest I can provide a PR.

**Comment by kal** [comment]
Hi Giacomo - that does sound interesting and a useful way to optimise the evaluation of the Service algebra. Are you planning to implement this by updating the code in Libraries\dotNetRDF\Query\Algebra\Service.cs?

**Comment by giacomociti** [comment]
Yes, I just opened a PR so you can have a look at the code
