### ISSUE TITLE
Graphs aren't re-cached

### ISSUE THREAD

**Issue by co2chicken** [dotnetrdf/dotnetrdf#396]
When a previously cached file exceeds the `UriLoader.CacheDuration`, the file is deleted and a new graph is fetched and put in its place. However, Windows sets the `CreationTimeUtc` property of the newly created file to that of the deleted file. Thus, the file can never be re-cached and is always re-fetched. This problem is described in this [StackOverflow](https://stackoverflow.com/questions/8804342/windows-filesystem-creation-time-of-a-file-doesnt-change-when-while-is-deleted)

As in the SO, I'd recommend adding a `File.SetCreationTime()` whenever a file is saved in cache to avoid this problem.

In the meantime, the workaround I've found is to completely delete old files from my cache directory and wait several minutes.

**Comment by kal** [comment]
Thanks for the report. I think I have found a reasonable fix for this issue so it will go into the upcoming 2.7.1 release.
