### ISSUE TITLE
FileGraphPersistenceWrapper throws null exception when flushing to disk

### ISSUE THREAD

**Issue by DarkOoze** [dotnetrdf/dotnetrdf#397]
### Issue:
Unable to persist changes from FileGraphPersistenceWrapper to disk.

### Steps to Reproduce the Problem:
 * Open FileGraphPersistenceWrapper from disk using the FileGraphPersistenceWrapper(string filename) signature
 * Save to disk using Flush or Dispose

```csharp
var wrapper = new FileGraphPersistenceWrapper("file.nt");
wrapper.Flush(); // Throws as _filename is not set by the constructor.
```

### Version
NuGet package Version="2.7.0"

**Comment by kal** [comment]
Thanks for the report. I've fixed this for the 2.7.1 release
