### ISSUE TITLE
Bug: QueryBuilder.InlineData() exception

### ISSUE THREAD

**Issue by jiatao99** [dotnetrdf/dotnetrdf#406]
Is there anyway to bind a list of value to a variable in the QueryBuilder?

The SPARQL below runs fine:

```
select ?key ?value
where {
    VALUES ?classes {ods:BusinessGroup ods:DataSourceType ods:NPDBusinessStatus }
    ?key a ?classes ;
       ods:hasName ?value
}
```

When I do the following, I got count not match exception (or can not convert Uir[] exception)

```
var buiilder = QueryBuilder.SelectAll();
// this line throw exceptions
buiilder.InlineDataOverQuery("classes").Values(new Uri("..."), new Uri("...")  });
// this line also throw exceptions
buiilder.InlineDataOverQuery("classes").Values(new object[] { new Uri("..."), new Uri("...") } });
```

**Comment by shuskey** [comment]
I am also having this problem, are there any solutions or work arounds for this?

**Comment by kal** [comment]
The `.Values()` method adds a single binding for the inline data variable(s). The reason it accepts multiple arguments is that inline data can be used to bind multiple variables so you can have multiple values in a single binding.
The correct way to provide multiple VALUES bindings is to repeat `.Values()` once for each binding:

```csharp
var builder = QueryBuilder.SelectAll();
builder.InlineData("classes")
    .Values(new Uri("http://example.org/a"))
    .Values(new Uri("http://example.org/b"));
var query = builder.BuildQuery();
```

Results in the query string:

```sparql
SELECT * WHERE { VALUES ( ?classes )
{
  ( <http://example.org/a> )
  ( <http://example.org/b> )
}
}
```

Whereas:

```csharp
var builder = QueryBuilder.SelectAll();
builder.InlineData("classA", "classB")
    .Values(new Uri("http://example.org/a"), new Uri("http://example.org/b"));
var query = builder.BuildQuery();
```

results in the query string:

```sparql
SELECT * WHERE { VALUES ( ?classA ?classB )
{
  ( <http://example.org/a> <http://example.org/b> )
}
}
```

Note also that you should use `.InlineData()` not `.InlineDataOverQuery()` as the latter binds the values outside of the root graph pattern.
