### ISSUE TITLE
Support JSON-LD as an RDF format

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#41]
_Imported from http://www.dotnetrdf.org/tracker/Issues/IssueDetail.aspx?id=71_

JSON-LD is becoming a popular alternative JSON serialization for RDF, add support for JSON-LD in terms of both parsing and serialization

---

Rob Vesse (Thursday, March 13, 2014 5:10 PM) #

The NuGet folks have some prototype implementation at https://github.com/NuGet/NuGet.Services.Metadata/tree/master/src/JsonLDIntegration/JsonLDIntegration

**Comment by markdwood** [comment]
I am bit confused -  NTriplesWriter, RdfXmlWriter implement interface IRdfWriter, whereas JsonLdWriter instead implements interface IStoreWriter?

**Comment by tpluscode** [comment]
Because JSON-LD serialized datasets, like N-Quads. Other formats you mention can only handle one graph in a single document

**Comment by markdwood** [comment]
Thanks, got it.   I was taking the result of doing a SPARQL Query (SparqlConnector.Query) which returns an object of type Graph.  Unless there's a better way(???) when saving to JSON-LD, I will create a temporary TripleStore, add the graph, and then serialize.

**Comment by kal** [comment]
You do need to wrap your graph into a store. Fortunately there is an extension method `AsTripleStore` for IGraph in VDS.RDF.GraphExtensions that will do this for you:

```C#
var store = myGraph.AsTripleStore();
```

**Comment by markdwood** [comment]
It appears the JSON-LD writer currently doesn't leverage the JSON-LD @context mechanism.   Are there plans to add that capability?

Also, I have literals that are of type "http://www.w3.org/2001/XMLSchema#decimal".  I see that when using the option UseNativeTypes, these values do not get serialized to the JSON native type -- is that be design?  Seems like they could get output as JSON decimal values.  (The data was originally read in as Turtle, and floating point numbers written in standard (non scientific) notation are read as being xsd:decimal).  Thanks.

**Comment by markdwood** [comment]
Kal - thanks for the comment.  However, the extension method AsTripleStore is marked internal currently.

**Comment by kal** [comment]
Currently the writer doesn't expose an option to set the context. However you can use the `SerializeStore` method on JsonLdWriter and then use VDS.RDF.JsonLd.JsonLdProcessor.Compact() to compact the output using a context you provide. It would probably make sense to add an option to do this by passing a context as part of the JsonLdWriterOptions.

With regards to the datatypes, I'm following the spec (or at least the version of the spec that was published when I wrote the code) which doesn't explicitly mention xsd:decimal. It does seem odd that they missed that one out, though I suppose that it could be because a JSON number is floating point and so doesn't really match the expectations of decimal. Again maybe its something that could be extended with a custom option, but then it means going beyond the spec.

**Comment by kal** [comment]
Ah so it is! That serves me right for not reading the code closely enough! Well the implementation is simple enough to wrap up as your own extension method or just stick into your code wherever it is needed. Maybe we could make that method public though, it is kinda useful...

```C#
TripleStore store = new TripleStore();
store.Add(g);
return store;
```

**Comment by markdwood** [comment]
On the datatype, I see what you are saying -- the W3C  JSON-LD 1.0 spec only mentions xsd:double and xsd:integer.   If an object internally is of type XmlSchemaDataTypeDecimal, then I believe serializing it as a number would result in a legal JSON numeric value, which, when deserialized from JSON-LD, would be either taken to be an xsd:integer or an xsd:double.

This issue arises because in Turtle, any non integral numeric value is an xsd:decimal, not an xsd:double, unless the number happens to be written in scientific notation.

I guess if one wants to preserve the datatype exactly as is between Turtle and JSON-LD, you're forced to do what you did, but in practice it would be helpful (and more compact) to have xsd:decimal just output as a plain numeric JSON value.

**Comment by markdwood** [comment]
BTW, what are the plans for NuGet releases?  Is that being done?  (Should I expect to see the JSON-LD support show up in a NuGet release at some point?)

**Comment by kal** [comment]
You should be able to find it in the most recent 2.0 pre-release

**Comment by markdwood** [comment]
Okay, thanks.  Hadn't noticed that version was now available; my mistake.
