### ISSUE TITLE
Feature Request/Question: RDF* star and Sparql Star

### ISSUE THREAD

**Issue by Davit18** [dotnetrdf/dotnetrdf#411]
I would like to know are you going to add support for rdf star, like adding new mime type with required implementations??

**Comment by kal** [comment]
I'm not sure about the timeline, but this feels like it is a good feature request for the 3.0 release. It certainly involves quite a lot of work dealing with the innards of the library so may take a while. If any experienced dotNetRdf developers/contributors are interested in helping out please let me know.

I've created an rdf-star label for issues relating to this work and I'll start to outline what I think those are based on my understanding of the [latest editors draft of the RDF-* CG spec](https://w3c.github.io/rdf-star/cg-spec/editors_draft.html). If you have any comments or thoughts on those please feel free to add them to the tickets and if you think something is missing please raise a ticket for that.

**Comment by kal** [comment]
Just a quick note that I've now outlined what I think the main tasks are - happy to take an feedback / comments on them and to accept new tickets for additional things you feel I might have missed.

**Comment by Davit18** [comment]
Thanks for quick response @kal  .

I'm new in all this staff, but our side plans to migrate to star. One more question if you don't mind, are there any approximate timeline when this 3.0 release or patch for star will be available, like end of year or maybe in a year?
thanks

**Comment by kal** [comment]
Hi @Davit18. I'm not really sure of the timeline at this stage. There are a couple of issues here - firstly this isn't part of my day job so working on it will require some free time; secondly the RDF-Star spec is still in draft which means it may change as I'm working on it (sometimes the changes are small, sometimes it can be quite a pain). I think my goal would be to have something reasonably complete in 4-6 months (so Q1 next year), but maybe with core model and parser/serializer support added before that. 

What would really help me is if you can follow on that work (maybe follow the tickets I've created) and test out things as they are committed to the development branch and let me know of any problems you find.

**Comment by lambdakris** [comment]
Hi @kal, could you point me to the individual issues you created to track rdf-star/sparql-star support?

**Comment by kal** [comment]
Hi @lambdakris : Take a look [here](https://github.com/dotnetrdf/dotnetrdf/issues?q=is%3Aissue+label%3Ardf-star+)
