### ISSUE TITLE
nuget prerelease of 3.0

### ISSUE THREAD

**Issue by sandrock** [dotnetrdf/dotnetrdf#435]
Hello,

I observe good stuff being done in the 3.0 branch. 

Would it be possible to prepare a pre-release nuget package? Or is it too soon?

**Comment by kal** [comment]
It's nearly there I think. I had been planning to hold off until I could get some docs written that at least cover the major "what has changed", but I could be persuaded to start kicking out pre-release packages before that as lng as you don't mind having to feel your way around APIs which might be in a bit of flux between releases.

**Comment by sandrock** [comment]
Here is an update of my demand; which I have to cancel. 

FYI I'm new to using this library. After trying to use various classes I found out that I can't use the latest 2.7.2 version because the (outrageous) dependency requirements are too high. 

I am now using 2.2.0 and will probably never will be able to use a superior version. (maybe I'll start a fork if I need some of the newer things)
