### ISSUE TITLE
TurtleWriter() eliminates crucial triple

### ISSUE THREAD

**Issue by christinekaush** [dotnetrdf/dotnetrdf#450]
Hi,
I'm trying to send a shape (graph) containing `sh:alternativePath` (see qoute below) through the TurtleWriter, but the triple `_:b1 sh:alternativePath _:b2` is missing in the processed graph, and therefor misses the connection for the sh:alternetivePath list.

> x:SomePropertyShape
        rdf:type        sh:PropertyShape ;
        sh:datatype     xsd:date ;
        sh:lessThan     x:oneWay;
        sh:maxCount     1 ;
        sh:minCount     1 ;
        sh:path         [ sh:alternativePath  ( x:A x:B )] .

Is this because both the subject and the object is of NodeType blank node? Or is the `sh:alternativePath` predicate not supported?

I have chosen the W3C for turtle syntax, but also tried the 'Original'. Moreover, I've tried _CompressingTurtleWriter()_ and the different compression levels as well, but the one triple containing `sh:alternativePath` is always missing..
> private string ToTtl(IGraph graph)
        {
            var writer = new TurtleWriter(TurtleSyntax.W3C);
            var text = new System.IO.StringWriter();
            writer.Save(graph, text);
            return text.ToString();
        }

**Comment by kal** [comment]
That's strange. I tried to reproduce the error with a simple test locally but when I serialize the data through the CompressingTurtleWriter I get:
```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix x: <http://example.org/>.
@prefix sh: <http://www.w3.org/ns/shacl#>.

_:autos778 rdf:first x:A;
           rdf:rest _:autos779.
_:autos779 rdf:first x:B;
           rdf:rest rdf:nil.
x:SomePropertyShape a sh:PropertyShape;
                    sh:datatype xsd:date;
                    sh:lessThan x:oneWay;
                    sh:maxCount 1 ;
                    sh:minCount 1 ;
                    sh:path [sh:alternativePath _:autos778].
```
I also tried a quick test for just writing a triple with a blank node subject and object and that passes the basic roundtrip testing for all of the syntaxes. So my guess is that somehow that triple is not making it into the graph that you are passing in to your `ToTtl` method. Do you have any code you can share that is constructing the triples?

**Comment by christinekaush** [comment]
Hm, then I'll have to look further into my code. When I debug all the triples are present in the step before, but disappear when I look at `text` after `writer.Save(graph, text);` ...
The triples are obtained by running a SPARQL request to a TopBraid-ontology, and all the triples are present there.

I'm actually trying to run a SHACL-validation but get a '500' error, which usually means that the triples are incorrect, and I noticed that the triples sent for validation gets a blank sh:path (`x:SomePropertyShape sh:path [ ]`).

But thank you for testing it out! Then I at least know that TurtleWriter()/CompressingTurtleWriter() is working as it should :)
