### ISSUE TITLE
Conditional insert not happening

### ISSUE THREAD

**Issue by giacomociti** [dotnetrdf/dotnetrdf#456]
Given an empty triple store, the following command should succeed:
``` sparql
PREFIX : <http://test/>
INSERT { :s :p :o } WHERE { FILTER NOT EXISTS { :s :p ?o } }
```
but actually nothing is inserted.

I noticed [here](https://github.com/dotnetrdf/dotnetrdf/blob/bc45d7cc9aa3959e252cf11a71c2247675332264/Libraries/dotNetRDF/Query/Algebra/Filter.cs#L74) that the variable `?o` causes the `IdentityMultiset` to be turned into a `NullMultiset`. There is also a comment explaining why but I'm not able to understand it.

**Comment by kal** [comment]
I think that check might be the problem. It looks like it is an attempt to avoid evaluating the filter - which I think probably works for an EXISTS filter, but not for NOT EXISTS. I think if NOT EXISTS was processed with that input, it would correctly return true and so the input IndentityMultiset should then get used as the output multiset for the filter step. I'd need to create a few tests for different combinations to be absolutely sure though.
