### ISSUE TITLE
Consider options for supporting parsing quad formats into a single graph

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#487]
Formats such as TriG, NQuads and JSON-LD all allow a document to specify triples in multiple graphs (i.e. quads). To read data from these formats it is currently necessary to use a `TripleStore` as the target rather than a `IGraph`. While this is generally not a problem if you are writing code to deal with a specific format, it can be a bit of a problem if you are using the `Loader` static class helper methods because invkoing the methods that use an IGraph target will not invoke the quad format parsers even if the source data is in fact all a single graph.

There are several different ways we could go on this:

- We could remove the helper methods that target an IGraph entirely from `Loader`. Triple syntaxes such as Turtle can still be read into a `TripleStore` - resulting in a `TripleStore` with a single graph. This is probably the cleanest way (and may point towards deprecating IGraph as the standard way of working with RDF data in the documentation).
- We could implement a loading shim that sits between the quad format parser and the target graph and either:
  - drops all quads that are not in the default graph (this could either be a graph with no name or a graph with one of the well-known names for the default graph).
  - drops all quads that are not in a graph that the calelr has configured on invoking the loader (though this again pushes the reponsibiltiy onto the caller to be aware of the possibility of receiving quads)
  - drops all quads that are not in the first graph encountered in the parsed data stream (so effectively only loads a single graph from the source)
  - throws an exception when it encounters a second distinct graph in the parsed data stream
  - merges all quads into a single graph

This ticket is spawned from the discussion on #484

**Comment by kal** [comment]
Considering the different options:

* Dropping the Loader methods that accept an IGraph target would be a breaking API change
* Implementing a loading shim would extend functionality (by allowing quad formats to be parsed into an IGraph target). Of the different options suggested, merging all quads would probably be the expected behaviour if a user deliberately used an IGraph target to load a source that they already know contains multiple graphs.

**Comment by ddeschepper** [comment]
@kal This issue seems to be blocking the release of the [3.2 milestone](https://github.com/dotnetrdf/dotnetrdf/milestone/25). Since there are quite some nice features and bugfixes waiting to be released, could you consider releasing a 3.1.2, or moving this issue to the [3.2 milestone](https://github.com/dotnetrdf/dotnetrdf/milestone/26)?
