### ISSUE TITLE
QueryWithResultGraph issue

### ISSUE THREAD

**Issue by vadimasg** [dotnetrdf/dotnetrdf#488]
When trying to run a method QueryWithResultGraph against Ontotext GraphDB, getting the following error:
The Library does not contain any Parsers for RDF Graphs in any of the following MIME Types: application/sparql-results+json;charset=UTF-8
The method QueryWithResultSet works just fine. What might be the issue?

**Comment by kal** [comment]
The query you are executing is probably a SPARQL `SELECT` or `ASK` query - these only return tabular results so there is no results graph and `QueryWithResultSet` is the correct method to use. `QueryWithResultGraph` should be used for `CONSTRUCT` or `DESCRIBE` queries.
