### ISSUE TITLE
What is pellet server ?

### ISSUE THREAD

**Issue by hosseinzareh** [dotnetrdf/dotnetrdf#502]
hi
how to define pellet server for reasoning in dontnetrdf?
we can define rdf contained rules  ad a pellet  server or not ?

https://dotnetrdf.org/api/html/M_VDS_RDF_Query_Inference_Pellet_PelletServer__ctor.htm
please descibe with a question.

**Comment by kal** [comment]
Hi,

Please take a look at https://dotnetrdf.org/docs/2.7.x/user_guide/Inference-And-Reasoning.html and https://dotnetrdf.org/docs/2.7.x/user_guide/Configuration-Reasoners.html for more information about the support for reasoners. The support for Pellet server is quite old, so if you find some issues with it, please report a bug!
