### ISSUE TITLE
OntologyGraph missing implementation for IRefNode Name

### ISSUE THREAD

**Issue by amanullahusmani** [dotnetrdf/dotnetrdf#509]
`3.0.0-rc0002` release implementation for `IGraph` constitutes of `IRefNode Name { get; }` for the named graphs.

While the class `Graph : BaseGraph` have a constructor with `IRefNode` as parameter to support named graphs, `OntologyGraph : Graph` have no parameterized constructor. Hence every `OntologyGraph` is unnamed default graph, as `Name` is `NULL`.

Should there be a parameterized constructor to resolve this?

```
OntologyGraph(Uri name) : base(name)
{
    this.NameSpaceMap.AddNameSpace("owl", this.uriFactory.Create("http://www.w3.org/2002/07/owl#"));
}
```

**Comment by kal** [comment]
Thanks for the report. You are right, there should be a constructor parameter to allow you to pass through the graph name on this class and on a few others that derive from Graph/BaseGraph/WrapperGraph. I've just pushed a change to address this and if all is well with the CI build I'll tag a new release candidate later this evening.

**Comment by kal** [comment]
v3.0.0 RC4 is now on NuGet. Hopefully this should fix the issue for you but please reopen this ticket if it doesn't!

**Comment by amanullahusmani** [comment]
Is it possible to have an implementation of `VDS.RDF.Ontology.OntologyGraph` more constructors that aligns with `VDS.RDF.Graph` i.e.:

```
OntologyGraph(IRefNode graphName = null) 
        : base(graphName)
{
    this.NameSpaceMap.AddNameSpace("owl", this.uriFactory.Create("http://www.w3.org/2002/07/owl#"));
}

OntologyGraph(Uri graphName) 
        : this((IRefNode) new UriNode(graphName))
{
   
}
```

Reason is to have consistency in instantiating a _graph_, for example creating graph instances through reflection.
