### ISSUE TITLE
[Reopen] - OntologyGraph missing implementation for IRefNode Name

### ISSUE THREAD

**Issue by amanullahusmani** [dotnetrdf/dotnetrdf#514]
With reference to #509 

Is it possible to have more implementations of `VDS.RDF.Ontology.OntologyGraph` constructors that aligns with `VDS.RDF.Graph` constructors i.e.:

```
OntologyGraph(IRefNode graphName = null) 
        : base(graphName)
{
    this.NameSpaceMap.AddNameSpace("owl", this.uriFactory.Create("http://www.w3.org/2002/07/owl#"));
}

OntologyGraph(Uri graphName) 
        : this((IRefNode) new UriNode(graphName))
{
   
}
```

Reason being having consistency in instantiating a _graph_. For example, let's say creating graph instances through reflection.

**Comment by kal** [comment]
Yes, that makes sense. Thanks for the suggestion
