### ISSUE TITLE
Support for the RDFa Initial Context

### ISSUE THREAD

**Issue by IS4Code** [dotnetrdf/dotnetrdf#523]
Currently, the RDFa parser ignores properties in HTML that don't use a defined namespace, but a lot of these are commonly used, for example using [`og:`](https://ogp.me/). I think it should be possible to specify a list of known prefixes, or to load one automatically from the [RDFa Core Initial Context](https://www.w3.org/2011/rdfa-context/rdfa-1.1.html) ([JSON](https://www.w3.org/2013/json-ld-context/rdfa11)). Custom sources may also be supported, like [prefix.cc](https://prefix.cc/) ([JSON](https://prefix.cc/context)). Not sure if downloading the context automatically would be allowed, but in any case, it should at least be possible to be able to specify which namespaces are pre-defined. Currently (as far as I know), this can be only done by inheriting from `RdfAParser` and overriding `GetAttributeValue` to change the `prefix` attribute.

**Comment by kal** [comment]
#563 extends the parser to support passing in an initial context as one of the parser options. It now defaults to using the context defiend for RDFa+XHTML but I've also provided a statically defined context for RDFa core and you can load your own context definitions from a graph.
