### ISSUE TITLE
Support Sql Server SQL Graph

### ISSUE THREAD

**Issue by wstaelens** [dotnetrdf/dotnetrdf#526]
https://learn.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-sample?view=sql-server-ver15
https://codingsight.com/how-to-make-use-of-sql-server-graph-database-features/ 
https://www.red-gate.com/simple-talk/databases/sql-server/t-sql-programming-sql-server/sql-server-2019-graph-database-and-shortest_path/

If this could be supported in SQL Server Express it could be very widely be used.

**Comment by kal** [comment]
Thanks for the suggestion, but I think this would be a fairly major piece of work to undertake as SQL Server provides no native SPARQL or RDF support so everything would have to be implemented by the integration. Right now there are not many active contributors to the project and I don't think it is likely I would have the time to work on this myself.
