### ISSUE TITLE
Trouble upgrading to 3.0.0-rc0004

### ISSUE THREAD

**Issue by bcalco** [dotnetrdf/dotnetrdf#541]
I am trying to upgrade all my solution projects to use 3.0.0-rc0004 (from stable 2.7.5) in anticipation of a hopefully immanent 3.0.0 final release, but running into a puzzling build problem on one of my projects.

I am getting the following four errors, all of them in the same project (none of the other upgraded projects seem to have this problem):

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'SparqlResultSet' is defined in an assembly that is not referenced. You must add a reference to assembly 'dotNetRdf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.	adb	C:\projects\dotnet\apex-build\src\Accelerate\adb\Commands\QueryCommand.cs	169	Active
Error	CS0012	The type 'ISparqlQueryProcessor' is defined in an assembly that is not referenced. You must add a reference to assembly 'dotNetRdf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.	adb	C:\projects\dotnet\apex-build\src\Accelerate\adb\Commands\QueryCommand.cs	100	Active
Error	CS0012	The type 'ISparqlQueryProcessor' is defined in an assembly that is not referenced. You must add a reference to assembly 'dotNetRdf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.	adb	C:\projects\dotnet\apex-build\src\Accelerate\adb\Commands\QueryCommand.cs	108	Active
Error	CS0012	The type 'IGraph' is defined in an assembly that is not referenced. You must add a reference to assembly 'dotNetRdf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.	adb	C:\projects\dotnet\apex-build\src\Accelerate\adb\Commands\QueryCommand.cs	139	Active
```

I tried cleaning and rebuilding, restarting the IDE, but they would not go away. I wonder why it says version "3.0.0.0" and not "3.0.0.0-rc0004." Why only this project (of the several whose references I upgraded) I have no idea.  Also, dotNetRdf is plainly referenced according to NuGet Package Manager, along with all its friends it includes as part of the installation.

My other beef (minor but real) is lack of a strong name key. It causes me problems as I need to deploy to an environment that requires them (yes, some still exist) and solutions like StrongNamer seem to use too much magic in that they bork some third party controls and thereby the UI designer when I add it to one of the projects that uses it.

Anyway - strong name key I can add myself on a custom build if it comes to that. But the errors above made no sense and I had to back out of upgrading for now. Which I really wish I didn't have to because I'm going to have to face the breaking changes later rather than sooner, and I'd prefer sooner.

**Comment by bcalco** [comment]
Oh and do you have an ETA on 3.0.0 final?

**Comment by kal** [comment]
A while ago we did have a short discussion about the strong naming and that conversation leaned towards not signing the assemblies any more. However your comment here prompted me to try and find if there was any recommended best practice around this for packages published on NuGet and what I found was https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming (TL;DR - strong naming is recommended). So I'm open to reintroducing the strong naming with the original key (kept in source control as recommended by that article). 

If anyone wants to weigh in with a counter argument this is the time to do it!

**Comment by kal** [comment]
I wonder if the upgrade difficulties are related to the lack of strong name - perhaps there is a rogue reference to the strong name in your projects?

**Comment by kal** [comment]
> Oh and do you have an ETA on 3.0.0 final?

I'm afraid not ATM.

**Comment by bcalco** [comment]
> I wonder if the upgrade difficulties are related to the lack of strong name - perhaps there is a rogue reference to the strong name in your projects?

Doubtful because prior to this attempt to upgrade I was using was 2.7.5. I thought maybe one of your assemblies has the reference but it only happens in that one project and I tried many ways of completely cleaning it, and yet it kept happening.

I do think it's significant that rc-004 was not part of the descriptor it was looking for. But I don't really have an explanation how that could be.

**Comment by bcalco** [comment]
> > Oh and do you have an ETA on 3.0.0 final?
> 
> I'm afraid not ATM.

Weeks? Months? Years? :)

**Comment by kal** [comment]
@bcalco - Do you have any further information for us about the upgrade errors?

**Comment by bcalco** [comment]
@kal - I will give it another try this afternoon. I created a new app to test a fresh installation of the 3.0.0.0rc4 version and it worked, but I have not had time to attempt the upgrade again on my real project. Will do so shortly and let you know how it went.

**Comment by bcalco** [comment]
@kal - I tried again and got the same errors as above. I wonder if this failure of StrongNamer isn't related:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The "StrongNamer.AddStrongName" task failed unexpectedly.
System.MissingMethodException: Method not found: 'Void Mono.Cecil.WriterParameters.set_StrongNameKeyBlob(Byte[])'.
   at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, Byte[] keyBytes, StrongNamerAssemblyResolver resolver)
   at StrongNamer.AddStrongName.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	adb			

```

**Comment by bcalco** [comment]
@kal - Indeed, removing StrongNamer the project now compiles (the warnings reported above go away) but because my assembly is strongly named, I get the following:

```
C:\data\learning-sparql>adb dba query --query ex003.rq --data ex002.ttl
Unhandled exception: System.IO.FileLoadException: Could not load file or assembly 'dotNetRdf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. 
...
```

**Comment by bcalco** [comment]
So please, for .NET Framework on Windows, at least, strong naming is not something I can do without.

**Comment by bcalco** [comment]
@kal - so obviously what was happening was StrongNamer was adding a key to dotNetRdf and that was causing assemblies that needed it to be unsigned to fail to load it. StrongNamer was failing at some point in the process on top of that. In general, while StrongNamer is very clever, it seems to be too clever by half in some situations. (It was also borking some third party components I use in a UI.) So in general, the problem will indeed go away when you sign the assemblies again.

**Comment by kal** [comment]
Thanks for the update @bcalco. I've pushed changes to main to reintroduce the assembly signing. I've set it up so that the signing is using the so-called [Public signing approach](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/security#publicsign). The MS docs indicate that this should be sufficient for most strong naming requirements and given that our private key is in a public repo, this is probably the best route to go down I think. Hopefully it should be enough for your strong-named assembly to be able to reference the DNR assemblies without having to use StrongNamer.

There's one minor issue with the release step of the build ATM because MS managed to break the `dotnet pack` command in the specific version of .NET 7 SDK that GitHub Actions is currently using :facepalm:  I've go a workaround for that in place now which works locally with the same version of the SDK as GH is using so with a bit of luck there should be some updated NuGet packages dropping soon for you to try out.

**Comment by bcalco** [comment]
@kal - Great! I'm eager to get using 3.0 asap.

**Comment by kal** [comment]
There is a new RC up now @bcalco . The assemblies in there should be signed and hopefully fix your upgrade issues. Let me know how it goes!

**Comment by bcalco** [comment]
@kal - Success!

Seems everything compiles and works after upgrading to rc6. Thanks!

I'll let you know if I run into anything that doesn't work but so far the basic sanity tests pass.

**Comment by kal** [comment]
Glad to hear it @bcalco ! I'll close this issue as fixed, but if you do hit any problems later please just open a new bug report.
