### ISSUE TITLE
Formatting/handling comments

### ISSUE THREAD

**Issue by IS4Code** [dotnetrdf/dotnetrdf#560]
I have a situation where I need to add logging information to the serialized RDF output, but there is no standard way to represent a handler that can process comments.

I could use something like this:
```cs
namespace VDS.RDF.Writing.Formatting
{
    public interface ICommentFormatter
    {
        string FormatComment(string text);
    }
}
```
Formatters could implement this interface, for example `TurtleFormatter` returning `"#text"`, `RdfXmlFormatter` returning `<!--text-->` etc. (with proper sanitization)

In addition, there could be a general way to inject comments into RDF data, such as:
```cs
namespace VDS.RDF
{
    public interface ICommentRdfHandler : IRdfHandler
    {
        bool HandleComment(string text);
    }
}
```
An implementation like `WriteThroughHandler` could then query the formatter from this method for the `ICommentFormatter` interface and write the comment line to the output.

What do you think about such an addition? I can implement this myself through a pull request, if needed.

**Comment by kal** [comment]
I think this sounds like a good extension to add. The design with the separate `ICommentFormatter` interface makes sense. 
Implementations would have to handle both string sanitization and also handling multi-line comments, but that logic properly belongs in the formatter implementations.

If we had `ICommentRdfHandler` as an extension of `IRdfHandler` then we could also potentially later extend some of the parsers to report comment strings, which might also be a useful feature. I wonder about just adding HandleComment to the existing `IRdfHandler` interface as a simplification, but the trouble with that is that it would introduce a breaking API change as all `IRdfHandler` implementations would have to be updated. So on balance `ICommentRdfHandler` is probably the way to go.

A PR to add this would be welcome if you have the time!

**Comment by kal** [comment]
Thanks for the PR! I've added this to the 3.1 milestone, but don't have a release date in mind, so please let me know if it is important for you to have "official" NuGet packages available.

**Comment by IS4Code** [comment]
Thank you too! I am in no hurry at the moment, so it can wait a few months for sure. 😃
