### ISSUE TITLE
Sign dotNetRdf.dll 3.0.x with a Strong Name

### ISSUE THREAD

**Issue by wiresio** [dotnetrdf/dotnetrdf#562]
Adding dotNetRdf.dll 3.0.0 to GAC does not work. Is working with 2.7.5.

```
gacutil /if dotNetRdf.dll
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failure adding assembly to the cache: Strong name signature could not be verified.  Was the assembly built delay-signed?
```

**Comment by kal** [comment]
The assemblies are now Public Signed which I believe is now the recommended way to approach signing assemblies. See the discussion on #541 for some of the background and links.

To install the assembly in the GAC you just need to resign it first. You can resign it with the project's key if you wish. e.g.

```
D:\Projects\dotnetrdf\Libraries\dotNetRdf.Core\bin\Release\netstandard2.0>sn -R dotNetRdf.dll d:\Projects\dotnetrdf\Build\dotNetRDF.snk

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'dotNetRdf.dll' successfully re-signed

D:\Projects\dotnetrdf\Libraries\dotNetRdf.Core\bin\Release\netstandard2.0>gacutil -i dotNetRdf.dll
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly successfully added to the cache
```

**Comment by sixdiamants** [comment]
The assembly VDS.Common.dll may also need resigning as per 
`sn -R C:\Users\bob_j\.nuget\packages\vds.common\2.0.0\lib\netstandard2.0\VDS.Common.dll .\VDS.Common.snk` 
(or whereever the assembly is stored). Lacking this, I got a verification of signature error.
