### ISSUE TITLE
Question regarding update of a Graph

### ISSUE THREAD

**Issue by hadlich** [dotnetrdf/dotnetrdf#60]
Hi,
I am not sure whether this is a bug or not - at the moment I am considering this as an question. (did not find a forum for users)

I have multiple sources, that I want to combine into one graph. - For instance I have German and English descriptions of the same concepts. Each source provides around 6000 - 12000 concepts.
If sources for different languages provide the same concept (same concept-id), I want to combine the information.
I am using the package from NuGet (package id="dotNetRDF" version="1.0.9.3683" targetFramework="net45" ).

The implementation is: 
- read the source
- insert the concepts + their properties per Graph.Assert() into the graph
(This is executed for each source, always on the same graph.)

Adding a concept to the graph is implemented like this:

    IUriNode conceptNode = _graph.CreateUriNode(UriFactory.Create(conceptId));
    _graph.Assert (new Triple(_g_dictionary,  _g_contains, conceptNode)); 

Adding Example property (Name):

     IUriNode nameNode = _graph.CreateUriNode(UriFactory.Create( Namespace + "Name"));
     ILiteralNode nameValue = graph.CreateLiteralNode(attribValue, language);
    _graph.Assert( new Triple(conceptNode, nameNode, nameValue);

When I add data from the second source, I execute exactly the same steps. Since the conceptNode already exists in the graph, it is not added. Only the property is added, so that the RDF reads:

`   <lia:Concept>`
`      <lia:Name xml:lang="en">Fire fighter</lia:Name>`
`      <lia:Name xml:lang="de">Feuerwehr</lia:Name>`
`    ...`
`   <lia:Concept>`
`</code>`

When I execute this for a small example everything works. All concepts have multi-language names.

The problem is:
When I execute this for my real data, this works only partially. - Some type of concepts do not get multi-language names (although an other property is updated). - I spend now two days of checking, the implementation is the same for all concept types (I am using the same method). 

There is a workaround:
When I store the graph after the first import, restart the program,  load the graph and import the second source, everything works as expected.

Can you give me any hint on what might be the source of the problem?

**Comment by kal** [comment]
Hi,

Since we closed down the old SF mailing lists there isn't a community forum so asking questions here is just fine!

I can't see a problem with the code that you posted, but it can be hard to spot bugs. Do you know if some of the expected properties that you can't find are actually getting added to the wrong concept or with the wrong predicate for example? 

I would suggest trying with cut down source files that include only the concepts that you have found issues with as then you could step through the code checking if the right triples are being added to the graph. 

Of course, if all you want to do is merge the two sources then your second approach would work just as well!

If you get more information by any of the investigations suggested above, please let me know here and we can work out if there is a dotNetRDF bug that needs fixing!

Cheers

Kal

**Comment by hadlich** [comment]
Hi Kal,
thank you for encouraging questions! :)

As far as I can see, the missing properties are not added to other concepts. - They are just missing.

The problem might be related to the size of the data (31 MB of XML-RDF at the first import, 53 MB at the second import.. ) or to some problem with initializing the data (since it works, when I load the stored RDF).

I will try to get more information, but since I have a workaround, I am focussing on other issues right now..

Best regards,
Thomas

**Comment by kal** [comment]
Cool - I'll close this issue for now. But feel free to reopen it when you have a chance to get a bit more information.

**Comment by rvesse** [comment]
One thing that springs to mind is whether this is a multithreading issue?

The standard  implementations are not thread safe so if you are manipulating the graph from multiple threads then you maybe stomping on each others changes and corrupting the underlying Data structures silently.

**Comment by rvesse** [comment]
The other possibility is some sort of a bug in the RDF/XML output. If you instead output your data as NTriples do you still see missing data?

**Comment by hadlich** [comment]
I think it is not related to multithreading. (It is a simple App, I do not use multiple threads.)

I am going to look at the possibility in the RDF/XML output. Since I am quite busy right now, I am going to research this next week.
