### ISSUE TITLE
RDF Dataset Canonicalization

### ISSUE THREAD

**Issue by veikkoeeva** [dotnetrdf/dotnetrdf#615]
I did not see an issue regarding this, so I record to make this visible. I hope this an OK way of doing this.

In W3C verifiable credentials linked proofs use  [RDF Dataset Canonicalization](https://w3c.github.io/rdf-canon/spec/). From the specification, the relevant part seem to be [§ 5. Serialization](https://w3c.github.io/rdf-canon/spec/#serialization). To my fairly untrained mind it looks like there are some smallish changes to n-quads, e.g.

[Example 8](https://w3c.github.io/rdf-canon/spec/#ex-ser-unique-hashes): Canonical N-Quads representation of Unique Hashes
```
This example illustrates the result of serializing the [canonicalized dataset](https://w3c.github.io/rdf-canon/spec/#dfn-canonicalized-dataset) described in [Example 2](https://w3c.github.io/rdf-canon/spec/#ex-ca-unique-hashes).

<http://example.com/p> <http://example.com/q> _:c14n0 .
<http://example.com/p> <http://example.com/r> _:c14n1 .
_:c14n0 <http://example.com/s> <http://example.com/u> .
_:c14n1 <http://example.com/t> <http://example.com/u> .
```

I think currently this library does not support creating n-quads in a canonical form like that. It may also be the changes needed for support are not vast, but I am not sure of that either. Maybe this issue could be used to enumerate changes needed to create canonical RDF Datasets by way of using this library (where make modifications, how and so on).

Currently there are projects on-going in EU and elsewhere where projects and standards implementations seem to be choosing between canonical JSON or canonical RDF when using self-sovereign identity concepts: decentralized identifiers, verifiable credentials, verifiable presentations and so on. Since signing documents is a core technical use case, inteoperability with .NET tools would be a large benefit.

Likely the canonical example implementation is at https://github.com/digitalbazaar/rdf-canonize.

**Comment by kal** [comment]
The main work here would be to implement the canonicalization algorithms in section 4 of the specification. The serialization of the canonicalized quads should be relatively easy to implement, but the canonicalization steps will take a bit more work and testing.

There is also a [test suite](https://w3c.github.io/rdf-canon/tests/) that should be integrated into the tests for the implementation.

**Comment by zotanmew** [comment]
I'm using dotnetrdf in a project that's building off of ActivityStreams, for which I need to implement linked data signatures, which needs JSON-LD canonicalization. I'm gonna try and see if I can get this working, and if so, open a pull request.

**Comment by zotanmew** [comment]
Quick update: Have a working implementation that passes all unit tests that only have first degree quads. Working on the rest now :)

**Comment by zotanmew** [comment]
83/84 passing tests, the last one is a unicode/encoding bug, opening a PR now. https://github.com/dotnetrdf/dotnetrdf/pull/618

**Comment by veikkoeeva** [comment]
What happened here? I mean... I need to be a bit offline and @zotanmew implemented it? Awesome is too mildly written. This is great, very great, @zotanmew! Thank you. :)
