### ISSUE TITLE
Can't load ontology from Web

### ISSUE THREAD

**Issue by fschumac** [dotnetrdf/dotnetrdf#62]
Hello everyone,

I have found a strange behavior, when trying to load a turtle-file into an Ontology graph

OntologyGraph o = new OntologyGraph();
if (isWebResource)
{ o.LoadFromUri(new Uri(my-resource-url)); }
else { FileLoader.Load(o, my-resource-path); }

If I load the [turtle-file](https://git.informatik.uni-leipzig.de/fschumac/MBO/raw/master/mbo.ttl) from my git repo, it fails with the message  

> Error loading ontology from [https://git.informatik.uni-leipzig.de/fschumac/MBO/raw/master/mbo.ttl]: [Line 2 Column 9] Unexpected Character (Code 111) o was encountered

If I load it from the local hard drive it works. Other ontologies, like [rdf](http://www.w3.org/1999/02/22-rdf-syntax-ns) or [foaf](http://xmlns.com/foaf/spec/index.rdf) can be loaded from the web.

Any idea what might cause the problem and how to solve it?

Thanks in advance,
Frank

**Comment by tpluscode** [comment]
I think the issue is with the `Content-Type` header on the response which is set to *text/plain*? 

Try calling `LoadFromUri` with a `TurtleReader` as second parameter.

**Comment by fschumac** [comment]
Hey, thanks for the reply!

It works with the XmlRdfParser :)
