### ISSUE TITLE
Canonicalized NQuads have `\r\n` as a linefeed when should be `\n`

### ISSUE THREAD

**Issue by veikkoeeva** [dotnetrdf/dotnetrdf#631]
According to the specification at https://w3c.github.io/rdf-canon/spec/#dfn-canonical-n-quads

> canonical n-quads form
 The canonicalized representation of a quad is defined in [A. A Canonical form of N-Quads](https://w3c.github.io/rdf-canon/spec/#canonical-quads). A quad in canonical n-quads form represents a [graph name], if present, in the same manner as a [subject](https://www.w3.org/TR/rdf11-concepts/#dfn-subject), and each quad is terminated with a single LF (line feed, code point U+000A).

At least on Windows the line feeds are `\r\n` in one way I tried. Consider the following snippet:

```
//Take some from https://json-ld.org/playground/.
var someJsonLd = ...
const PlayGroundCanonicalizedJsonLd = ...

 var canonicalizer = new RdfCanonicalizer("SHA256");
 using(var inputStore = new TripleStore())
 {
     var parser = new JsonLdParser();
     using(Graph g = new Graph())
     {
         parser.Load(inputStore, new StringReader(someJsonLd));
         var result = canonicalizer.Canonicalize(inputStore);
         
         //Here canonicalQuad has "\r\n" linefeeds on Windows at least.
         var canonicalQuad = result.SerializedNQuads;
         Assert.Equal(PlayGroundCanonicalizedJsonLd, canonicalQuad.Replace("\r\n", "\n"));
     }
 }
 ```

**Comment by kal** [comment]
Thanks for the report.
Looks like we need some extensions to the NQuads formatter to allow the default line-ending to be overridden. Currently the code uses `StringBuilder.AppendLine()` to write each quad which is why you end up with `\r\n` on Windows.
