### ISSUE TITLE
Incorrect handling of blank nodes in construct queries

### ISSUE THREAD

**Issue by JohanMollevikCap** [dotnetrdf/dotnetrdf#639]
When running this sparql query using the dotnetrdf 3.1.1 in memmory query processor

prefix data:<http://data.example.com/>
construct {
	[ data:subject ?s ; data:predicate ?p ; data:object ?o ] .
}
where {
	{
		select ?s ?p ?o
		where {
			bind(1 as ?s).
			bind(2 as ?p).
			bind(3 as ?o).
		}
	}
	union
	{
		select ?s ?p ?o
		where {
			bind("a" as ?s).
			bind("b" as ?p).
			bind("c" as ?o).
		}
	}
}

I get this result

_:autos1 http://data.example.com/subject 1^^http://www.w3.org/2001/XMLSchema#integer
_:autos1 http://data.example.com/predicate 2^^http://www.w3.org/2001/XMLSchema#integer
_:autos1 http://data.example.com/object 3^^http://www.w3.org/2001/XMLSchema#integer
_:autos1 http://data.example.com/subject a^^http://www.w3.org/2001/XMLSchema#string
_:autos1 http://data.example.com/predicate b^^http://www.w3.org/2001/XMLSchema#string
_:autos1 http://data.example.com/object c^^http://www.w3.org/2001/XMLSchema#string

I want this result (and that is what ontotext/graphdb returns), how do I get that

_:autos1 http://data.example.com/subject 1^^http://www.w3.org/2001/XMLSchema#integer
_:autos1 http://data.example.com/predicate 2^^http://www.w3.org/2001/XMLSchema#integer
_:autos1 http://data.example.com/object 3^^http://www.w3.org/2001/XMLSchema#integer
_:autos2 http://data.example.com/subject a^^http://www.w3.org/2001/XMLSchema#string
_:autos2 http://data.example.com/predicate b^^http://www.w3.org/2001/XMLSchema#string
_:autos2 http://data.example.com/object c^^http://www.w3.org/2001/XMLSchema#string

If I am reading the spec correctly the correct solution is the one I want so am
I correct in assuming that this is a bug.

Relevant section of the spec https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#templatesWithBNodes
I qoute "but there will be different blank nodes for triples generated by different query solutions"

**Comment by kal** [comment]
This does look like a bug in generating blank nodes in the CONSTRUCT.
