### ISSUE TITLE
Dokumentation: Where is "the" source?

### ISSUE THREAD

**Issue by Lercher** [dotnetrdf/dotnetrdf#64]
On http://dotnetrdf.org/content.asp?pageID=dotNetRDF%20Source%20Repository there are these links:

https://github.com/dotnetrdf/dotnetrdf.git
https://dotnetrdf.codeplex.com/

Under the "Source code" menu item: https://bitbucket.org/dotnetrdf/dotnetrdf

In various readme.md-s this git repository is not mentioned but it seems to have the latest commits. So it would be nice to place some clarifying and consistent words about this git repository in the readmes and on the .org website as well as a recommendation from where to get "the" sources and which issue tracker is used.

Furthermore the blog at dotnetrdf.org stops at version 1.0.8, but the latest version I've found is 1.0.12, so it would be nice to see a new blog entry mentioning the three newer versions.

Thanks, Martin

**Comment by kal** [comment]
Hi Martin,

All the latest source code is now on GitHub. The site and the docs all need updating. I want to move the main site off the elderly CMS that it is currently on and to GH pages, but it is just a question of getting the time to do it. In the meantime I'll at least try and fix some of those bad links that you found.

Cheers

Kal

**Comment by kal** [comment]
Fixed up the links mentioned and a few others on the CMS. But it is really crufty and there are probably some other links that I've missed. I've created another issue (#60) for the real task here which is to create a new site for dotNetRDF and redirect dotNetRDF.org there.

**Comment by Lercher** [comment]
Thank you very much for the clarification. PS: I'm personally happy that you moved to github, because subjectively I feel bitbucket quite cumbersome compared to github.

**Comment by Lercher** [comment]
PS: see #65, not #60
