### ISSUE TITLE
`TriGSyntax.Rdf11` should be the default value for the `TriGSyntax` enum

### ISSUE THREAD

**Issue by markus-ap** [dotnetrdf/dotnetrdf#640]
I think it it is misleading that the default value of the `TriGSyntax` enum is `TriGSyntax.Original` which is based on an [old proposal](https://www.w3.org/2010/01/Turtle/Trig) for how `TriG` should work, rather than the [current recommendation](https://www.w3.org/TR/trig/). 

I therefore suggest that the default value should be `TriGSyntax.Rdf11`, as this is the value used to parse TriG according to current recommendations.

Today if you initate a `TriGParser` it gets initiated with `TriGSyntax.Original` if you do not explicitly use the correct syntax. 

E.g.
`var parser = new TriGParser();` will give you a `TriGSyntax.Original` parser.

You have to do `var parser = new TriGParser(TriGSyntax.Rdf11);` to get a parser that parses the current `TriG` standard.

**Comment by eoye** [comment]
I agree with @markus-ap

**Comment by henriettelienrebnor** [comment]
I second this

**Comment by kal** [comment]
I think the default should actually be `TrigSyntax.Rdf11Star` because that would be consistent with the default in `TriGWriter` and also the defaults we have for Turtle, NTriples and NQuads.
