### ISSUE TITLE
GitHub Pages Site

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#65]
Create a new site to replace the venerable dotnetrdf.org CMS.

Now that we are here on GitHub, GH pages would make most sense.

**Comment by kal** [comment]
New site created at https://dotnetrdf.github.io/

@rvesse - would it be possible to create a CNAME entry so that dotnetrdf.org and www.dotnetrdf.org go to this new site instead of the old CMS?

**Comment by rvesse** [comment]
I have redirected www.dotnetrdf.org with a CNAME but I cannot do the same for the primary domain. 

Does the new site have a fixed IP address as I can only add A entries for the primary domain

**Comment by rvesse** [comment]
By the way the CNAME record doesn't seem to work, not sure if there is some config needed on this end to tell GitHub that www.dotnetrdf.org aliases to dotnetrdf.github.io?

**Comment by rvesse** [comment]
Yes looks like you need to change a repository setting - https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

**Comment by kal** [comment]
@rvesse - I've added the setting with www.dotnetrdf.org for now. The instructions for setting up the A record are at https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider. 
Thanks Rob!

**Comment by rvesse** [comment]
Done, now works for me

**Comment by kal** [comment]
Works for me too, thanks Rob!
