### ISSUE TITLE
JSON-LD DefaultDocumentLoader is vulnerable to excessive memory buffer allocation

### ISSUE THREAD

**Issue by zotanmew** [dotnetrdf/dotnetrdf#650]
DefaultDocumentLoader uses WebClient to fetch the response. WebClient defaults to (and this doesn't appear to be configurable) a 2GB maximum buffer size, which is likely excessive and unwanted, as it leaves machines running dotNetRdf to handle untrusted JSON-LD inputs vulnerable to remote excessive memory allocation.

I briefly tried to make WebClient cancel the request if the response is too long, but couldn't figure out how. I'd recommend switching to HttpClient instead.

**Comment by kal** [comment]
I'll look into how easy that would be to do without breaking our APIs.

**Comment by kal** [comment]
Hi @zotanmew ! Do the changes on the PR referenced above meet your needs? I chose not to expose the full HttpClient/HttpClientHandler but just to expose options to set response content size and max redirects. I guess that potentially there are other fields that other developers might want to be able to configure, but this seemed like a good basic start.

**Comment by zotanmew** [comment]
This looks great, yep!
