### ISSUE TITLE
What's the best practice for managing the lifecycle of LeviathanQueryProcessor within WebAPI?

### ISSUE THREAD

**Issue by RetYn** [dotnetrdf/dotnetrdf#655]
Hello, I'm currently working with the dotrdf package to develop a web API that queries in-memory RDF triples.
I assume there should be only one singleton object for InMemoryDataset
My question is : 
What's the best practice for managing the lifecycle of LeviathanQueryProcessor within WebAPI?
Is it advisable to instantiate a new LeviathanQueryProcessor for each incoming request, or is it possible to share a single instance across multiple requests?
Is it thread-safety if I only use for query?

**Comment by kal** [comment]
Hi,

It is possible to share the same LeviathanQueryProcessor across multiple threads. The implementation uses a read/write lock on the InMemoryDataset to ensure that no updates are carried out while there are reads in progress and supports concurrent reader threads, and concurrent queries are thread-safe.

**Comment by kal** [comment]
I think it would be good to add some notes about this to the documentation.

**Comment by RetYn** [comment]
Thanks for your reply!
