### ISSUE TITLE
QueryBuilder.BuildQuery does not optimise the returned SparqlQuery

### ISSUE THREAD

**Issue by RetYn** [dotnetrdf/dotnetrdf#658]
Here is the situation
I am following the example to use QueryBuilder to build sparql query on a grpah contains 70k triples (which is small).
The query process is LeviathanQueryProcessor
Here is the original code
```
            var queryBuilder = QueryBuilder.Select(variableList.ToArray())
            .Where((builder) =>
            {
                    foreach (var tripple in tippleList)
                        {
                            if (tripple.Object.Contains("foaf:"))
                            {
                                builder.Subject(tripple.Subject)
                                    .PredicateUri(tripple.Predict)
                                    .Object<IUriNode>(tripple.Object);
                            }
                            else
                            {
                                builder.Subject(tripple.Subject)
                                    .PredicateUri(tripple.Predict)
                                    .Object(tripple.Object);
                            }
                        }
            })
            .Filter((builder) => TriplePatternBuilderExtension.AggreateExpressionFromFilters(builder, filterList));
            var results = await processor.ProcessQueryAsync(queryBuilder.BuildQuery());
```
The original ttl file is only 5mb, but when run this code, the memory usage is rasing to 15GB and cannot return results because the program is blocking.

When I don't directly pass the output of queryBuilder.BuildQuery() to the processor, things work differently.
Consider the code below where I take the query text produced by queryBuilder's toString method and create a SparqlQuery from that string.
This queryBuilder is configured identically to the one in the previous example.
Under these conditions, the processor operates smoothly.
```
            var query = queryBuilder.BuildQuery().ToString();
            SparqlQueryParser queryParser = new SparqlQueryParser();
            var sparqlQuery = queryParser.ParseFromString(query);
            var results = processor.ProcessQuery(sparqlQuery);
```

Is there any bug in querybuilder? Or I create the queryBuilder wrong?

**Comment by kal** [comment]
Hi @RetYn ,

I notice that in your second example you are using `processor.ProcessQuery()` but in the first one you are using `processor.ProcessQueryAsync()`. Can you just check in your examples what happens if you use `processor.ProcessQuery()` in the first example. This is just to try and narrow down what the possible cause could be.

**Comment by RetYn** [comment]
@kal Sorry for the late respone.
I change the second to ProcessQueryAsync, it also works very well.
Right now I have applied this work aournd wary.
Curious, what happened in side.

**Comment by RetYn** [comment]
@kal 
Yes, after adding query.Optimise()  
It works.

**Comment by kal** [comment]
Cool! I think it would make sense for `BuildQuery` to optimize the `SparqlQuery` before returning it so that other users don't trip over this issue in future.

**Comment by kal** [comment]
In the next release the SparqlQueryBuilder will optimise the query it builds by default. The `BuildQuery` method has been extended to take two optional parameters which turn optimisation on/off and allow you to specify which query optimiser to apply, but the default will be to apply the statically defined default query optimiser (`SparqlOptimiser.Default.QueryOptimiser`).
