### ISSUE TITLE
Wrong Newtonsoft.Json reference in .Net Core version

### ISSUE THREAD

**Issue by rastocny** [dotnetrdf/dotnetrdf#66]
Hello, you have wrongly cased reference to Newtonsoft.Json. Wrong case leads to Nuget error due to duplicit loading of Newtonsoft.Json and Newtonsoft.JSON library: 
An item with the same key has already been added. Key: System.Collections Unspecified

https://github.com/dotnetrdf/dotnetrdf/blob/develop/Libraries/core/netcore/project.json#L21

**Comment by kal** [comment]
Well spotted, thank you!

**Comment by rastocny** [comment]
Thanks for fixing. Now it is working correctly.
