### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by alitedi** [dotnetrdf/dotnetrdf#67]
Hello Dear,
I'd like to do a query to this endpoint:
"http://publications.europa.eu/webapi/rdf/sparql". For doing it I use QueryWithResultSet function but there is an error 502 Bad Gateway.
If there will be a possibility for setting UserAgent of request, it can retrieve the data but there no option in dotNetRDF.
Could you help me?

Best regards
Alireza TADBIR

**Comment by kal** [comment]
@alitedi - did [this answer](http://stackoverflow.com/questions/40025957/insert-a-rdf-data-to-virtuoso-by-using-dotnetrdf-library-in-c-sharp-net) from Rob on StackOverflow answer your question about setting the user agent? 

If the endpoint is still giving a 502 error then it is possible that there is something wrong on their side as the response indicates that the server you are connecting to is acting as a gateway and it got an error from the upstream server that it connected to.

**Comment by alitedi** [comment]
I have used the answer of Rob by using Options.HttpDebugging and I saw that the Endpoint blocked me for accessing to their Endpoint !!!

Once again, thanks for your and Rob's response.
