### ISSUE TITLE
Wrong url at dotnetrdf.github.io to Github repository

### ISSUE THREAD

**Issue by Ubloobok** [dotnetrdf/dotnetrdf#68]
Page https://dotnetrdf.github.io/ has wrong url to GitHub repository.
Text "Our source code is on GitHub.", wrong url "https://github.com/dotnetrddf/dotnetrdf" (double **d**), which shows error "Page not found".
Should be one **d**.

**Comment by kal** [comment]
Fixed. Thanks!
