### ISSUE TITLE
TurtleParser.Load: "[Line 241 Column 43] The QName dbr:Bose–Einstein_condensate is not valid in Turtle"

### ISSUE THREAD

**Issue by jlewis111** [dotnetrdf/dotnetrdf#71]
TurtleParser.Load: "[Line 241 Column 43] The QName dbr:Bose–Einstein_condensate is not valid in Turtle"

I get the above error when running the following query against DBPedia:

CONSTRUCT
WHERE
{
     <http://dbpedia.org/resource/Albert_Einstein> ?p ?o . 
}

http://dbpedia.org/sparql/

i.e.:
http://dbpedia.org/sparql/?query=CONSTRUCT%0AWHERE%0A%7B%0A+++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FAlbert_Einstein%3E+%3Fp+%3Fo+.+%0A%7D

then when trying to load

               TurtleParser tp = new TurtleParser(TurtleSyntax.W3C);

               using (StringReader stringReader = new StringReader(queryResult))
                {
                    tp.Load(g, stringReader);
                }

This is probably down to the hyphen character being typed in from Microsoft Word and not being a standard ASCII character.

However, I would have though that Unicode names are allowed.

Please advise.

**Comment by jlewis111** [comment]
[response.txt](https://github.com/dotnetrdf/dotnetrdf/files/752954/response.txt)

**Comment by jlewis111** [comment]
Added Unicode reponse file above that was failing to load in TurtleParser.Load().

**Comment by kal** [comment]
I'm afraid that it looks like DNR is correct in that the particular character used in this file (0x2013) is not allowed in the QName production for either Turtle or Turtle 1.1. For reference please see the BNF at https://www.w3.org/TR/turtle/#sec-grammar-grammar - in particular PN_LOCAL and its sub-productions.
 
For this to be valid Turtle, the character would have to be escaped (or alternatively changed to a more sane hyphen ;-), both on the line reported and on several other lines in the file.

I'm going to close this as an invalid issue as it seems that DNR is following the spec, but thank you for taking the time to report this!
