### ISSUE TITLE
Ditch develop branch

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#74]
Multiple OS repositories out there work on a single branch `master`. Releases get a tag and new features/fixes always come in Pull Requests which are merged when ready. I'm not sure what the current is workflow but I'd get rid of `develop` in favor of a simpler workflow.

**Comment by kal** [comment]
Oh, controversial! :-)

Personally I've been really happy with a git-flow-like develop/master split. Keeping master "clean" and limited to merges in for releases feels better to me, especially as we don't do nightly builds or continuous delivery. Really the only difference to the workflow you suggest is that PRs are merged into develop and master is only updated on a release.

Which projects use this simpler workflow? Can you point me to one or two so I can take a look.

**Comment by tpluscode** [comment]
Here are some examples of popular libs/tools which only use `master` and feature branches: [Nancy](https://github.com/NancyFx/Nancy), [GitVersion](https://github.com/GitTools/GitVersion), [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json) [Dapper](https://github.com/StackExchange/Dapper)

**Comment by tpluscode** [comment]
On the other hand Autofac has both `master` and `develop` I'm not strongly in favor of either way. Although only having one branch should be enough with infrequent releases and only few changes

**Comment by kal** [comment]
This is true, and looking at the commit history on the Nancy and Newtonsoft.Json master branches it looks like a reasonable way of working.

I'm happy to go with ditching develop and moving over to PRs into master. We should also review all the other open branches and delete as many of them as possible.

Question: Should we keep a maintenance branch for 1.0.x ? Or just create it if needed using a release tag

**Comment by tpluscode** [comment]
> Should we keep a maintenance branch for 1.0.x ? Or just create it if needed using a release tag

Guess that answers my question under #82. I'm not sure which works best. It will probably be a little more visible with a permanent 1.x branch

**Comment by kal** [comment]
Develop branch is gone :-)
I've set the default branch for the repo to master.
