### ISSUE TITLE
Move to .NET Core/Standard

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#76]
@kal, I see that you created the [feature-dotnetcore-build](https://github.com/dotnetrdf/dotnetrdf/tree/feature-dotnetcore-build) branch. The NuGet packages also already come with .NET Standard builds although I don't see any `dotnet`-related stuff in the repo.

How would you feel about attempting to migrate to `project.json`. I know it's being replaced be new `csproj` but personally I've had a hard time getting VS2017 to work. Until it's ready and stable how about we try moving on. It should simplify to repository a great deal where we currently have the project sync and multiple csprojs for each target.

**Comment by tpluscode** [comment]
Oh, my bad. I completely missed the netcore folder. With `xproj`/`project.json` we should be able to have only a single project.

**Comment by tpluscode** [comment]
I've successfully converted a good portion of the libraries and unit tests. A problem I've encountered and don't how to overcome is wrt running tests against portable build. It seems it's not possible with current tooling, because `dotnet` test runner depends on 3rd party packages which don't target PCL.

@kal do you think we have to support PCL or maybe it would be possible to do down to .NETStandard 1.0 or 1.1 instead which cover most of the same platforms?

**Comment by kal** [comment]
IIRC there is a trade-off between functionality and platform support here. 

If possible I would be in favour of just building .NETStandard 1.0 and .NETStandard1.4 targets (with the former being probably as constrained in its features as our current portable library build is), and dropping all of the other variants (including the .NET 3.5 library support). This would possibly break builds for people still trying to support those older .NET platforms - but I'm not sure if there is anyone out there with that sort of hard requirement.

**Comment by kal** [comment]
@tpluscode - Can you commit what you have done so far as a separate branch. Then perhaps we can look at simplifying things further and at issues like PCL support.

**Comment by tpluscode** [comment]
Sure, I'll work some more on this to the point that at least libraries and tests work and I'll push a branch. And net35 isn't a problem unless we'd want to go for 4.5+

**Comment by kal** [comment]
Cool! 🍾 

I would like us to also look at splitting out all the non-core libraries (SPIN, FullText, and the tools) into their own separate GitHub projects and let them version at their own speed and in that way we can further simplify the  core library repository. So if you can just get to the point where the core libraries and their tests are working that would be really useful.

**Comment by tpluscode** [comment]
> their own separate GitHub projects

Agreed! I was thinking the same but about GUI tools.
