### ISSUE TITLE
Do we need assembly signing?

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#78]
I'm just in progress of cleaning up the solution and moving to package.json (see #76). It's been going fairly well until I hit the `InternalsVisibleTo` exposing stuff for testing. Apparently, it doesn't work with the old-new format.

Personally I'd just remove strong-naming altogether. What do you think @kal @rvesse?

**Comment by kal** [comment]
My concern is that it would break builds for anyone depending on referencing it from their own signed assembly. 

What exactly is the problem you have hit ? A quick Google for some SO questions related to InternalsVisisbleTo and package.json seems to indicate that it all Just Works, but I'm quite possibly missing something.

**Comment by rvesse** [comment]
I would tend to agree with Kal. While assembly signing may be a pain in the ass and we can probably all agree that it is a fairly broken concept nonetheless large parts of the ecosystem rely upon it. If you remove it trust me he will get a load of grief from people who were relying upon it that you never knew existed.

**Comment by tpluscode** [comment]
@rvesse you're right, I definitely wouldn't want to break people's code. And if it works with project.json for other people it should definitely works for us. I'll give it another try.

**Comment by kal** [comment]
I think we are all good with the assembly signing now, so closing this as a won't fix.
