### ISSUE TITLE
Getting a 2.0 out

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#82]
I'd like to get folks views on the next dotNetRDF release both in terms of its scope and its numbering.

Rob had started work on a complete redesign of the DNR API, slating it for a 2.0 release. However not a lot has been done on that recently, although I really do want to get around to it as there is a lot of good stuff in there and scope for really tidying up some of the rougher edges in the 1.0 API.

In the meantime, .NET has moved forwards and we really need to update the packaging of the library to reflect this. That means in particular migrating to .NET Core (see #76), and as a result possibly dropping support both for .NET 3.5 and for signed assemblies, both of which would break the build for those depending on them. 

Originally my plan was to work on 2.0 as a .NET Core library and leave 1.0 with its legacy" .NET platform targeting, but a 2.0 release (with the new APIs) is too far off.

So, I propose (spurred on by @tpluscode) to do some work now to get the existing DNR APIs built to target .NET Core (probably targeting the netstandard 1.0 and 1.4 platforms). 

So, should this release be numbered 1.1 or 2.0 ? My thought is that 2.0 would be a better choice because we know it is going to break some builds just because of the change in platform targetting. It also gives us the opportunity to look at some of the existing issues such as #79 where there are proposals to change existing APIs. Then that would mean that the full API redesign would be slated for a future 3.0 release instead and so would leave us with:

1.0.x = legacy platform targeting (.NET 3.5, .NET 4.0, PCL, Xamarin) & signed with the old key.
2.x = .NET Core build (netstandard 1.0 and 1.4), some minor API tweaks and breakages but for the most part API-compatible with 1.0.x
3.x = DNR-vNext with completely reworked APIS

How does that sound? @tpluscode, @rvesse any thoughts?

**Comment by tpluscode** [comment]
I think I agree. Cleaning up the build may or may not lead to actual breaking changes although going straight to 2.x would send a clear message that things have changes substantially. The opportunity to do some actually breaking but minor changes could also be good.

The only thing I'm worried about is merging any of those changes (both in build and library) into the future 3.x branch. I suspect that some of that work would have to be done twice.

Finally, do you propose supporting both 1.0.x and 2.x in the long run?

**Comment by kal** [comment]
The vnext (3.0?) API for DNR is so substantially different that I think library/code merges are simply not going to be feasible, and while it would be nice to be able to reuse the work you are doing now on the build, I suspect that it will be easiest to just create a new build from scratch. In fact I actually started work on moving the vnext API development into a separate repository (dotnetrdf2) - that gives you an idea of how separate I see it!

There are features and fixes that I really want to get to work on (such as JSON-LD support) and that might end up being work that we do in 2.0 and that gets ported to the 3.0 APIs at a later date, but even that I think is not going to be a straightforward merge, its going to be a manual port. I think we will just have to bite the bullet on that.

1.0.x I would like to support in parallel with 2.x for a little while, though I really hope that most people will migrate to 2.x so that we don't have a long overhang of "legacy" support.

**Comment by tpluscode** [comment]
So *dotnetrdf2* repository is the 1.9 branch turned into project.json, right?

> 1.0.x I would like to support in parallel with 2.x for a little while, though I really hope that most people will migrate to 2.x so that we don't have a long overhang of "legacy" support.

Yeah, if indeed most breaking changes are about targeted frameworks, we could hopefully be able to drop 1.0.x fairly soon.

**Comment by kal** [comment]
> So dotnetrdf2 repository is the 1.9 branch turned into project.json, right?

Yep. I guess we might need to rename that repo to avoid confusion! ;-)

So, the more I think about 1.x support, the less I think I like it. Given that the build system and the packaging will be so totally different, just doing support on it is going to be a pain and burn cycles we simply don't have. So I'm thinking we should take a radical approach here:

- Keep this (dotnetrdf) repo as the 1.x "legacy" repo. Note in the readme that this codebase is no longer supported but that folks are free to fork it if they want to do that for themselves
- Create separate repos for the libraries and tools and use these as our repos for 2.x development
- Create another repo (or just rename the existing dotnetrdf2 repo) for the vnext core library
- At some point the tools and other libraries will need to migrate to the vnext APIs, but we cross that bridge when (if!) we come to it.

Its a bit of a radical overhaul, but perhaps it would be better in the long run. Also restarting the core repo from scratch would also deal with that issue about the dotnetrdf repo being so huge due to historical large files.

What do you think, is this even sensible? :-)

**Comment by tpluscode** [comment]
Unless the existing repo becomes an issue, I wouldn't immediately cut it off completely. I think it may just be enough to keep the old codebase in a branch. Hopefully we won't even have to touch it ever :)

> Create separate repos for the libraries and tools

I agree about extracting the tools to a separate. I think I'll do a `git filter-branch` to retain history. 

> Create another repo (or just rename the existing dotnetrdf2 repo) for the vnext core library

Rename should be enough IMO

**Comment by kal** [comment]
I think we have a plan and its all under way now, so I'm closing this issue even though a 2.0 isn't actually out yet.
