### ISSUE TITLE
Clean up compiler flags and directives

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#93]
Due to historical reasons, the library and, to some extent, tests are generously sprinkled with `#if` flags

Here's @kal's original [comment](https://github.com/dotnetrdf/dotnetrdf/pull/84#issuecomment-286774666)

> One other thing I've noted is that the netstandard1.4 has compiler flags that exclude quite a lot of functionality. I originally put these in as a quick and dirty fix for the lack of compatible APIs in the target framework. It would be good to see if we can find a way to add back the support. The flags currently defined are:
> 
> - [x] NO_SYSTEMCONFIGURATION - this indicates that the System.Configuration.ConfigurationManager API is not available and disables support for the ConfigurationLoader. We could maybe add a NetcoreConfigurationLoader to replace this functionality using the .NET Core configuration APIs
> - [x] NO_PROXY - this indicates that the System.Net.WebProxy API is not available and disables proxy support in a number of HTTP endpoint implementations.
> - [x] NO_XSL - this indicates that the System.Xml.Xsl namespace is not supported. It disables support for XSL stylesheets in the TriX parser and disables the SparqlXsltWriter. I'm not sure there is anything we can do about this one.
> - [X] NO_HTMLAGILITYPACK - indicates that the HtmlAgilityPack library is not available. This means no RDFa parser amongst other things :-(
> - [X] NO_DATA - this indicates that the System.Data.DataTable API is not available. It just disables the APIs that allow graphs and SPARQL results to be acccesed as a DataTable, so not really a problem I think.
> - [x] NO_WEB - this has a huge impact in terms of supported features and needs a bit of careful review because I think that in many places we do have access to the required APIs. Needs further investigation.
> - [x] NO_PROCESS - indicates no support for starting external processes (ProcessStartInfo API?). Only used by the GraphVizGenerator class.
> - [x] NO_URICACHE - indicates that the VDS.RDF.Parsing.UriLoaderCache class is not included and disables the use of that cache in the UriLoader class.
>
>
> I think it would be worth going through each one and making a call on whether it stays in as a compiler flag or we do something to work around it for this target profile.

Out of those, the removal of `NO_HTMLAGILITYPACK` has already been removed with #91. Additionally there are some more which are only present in the source files. Some not needed anymore I think.

- [x] PORTABLE
- [x] NET_4_0
- [x] FULL_AOT_RUNTIME
- [x] WINDOWS_PHONE
- [x] NO_ASP - Compile without building the VDS.RDF.Web namespace which provides the ASP.Net integration.  Using NO_WEB will also cause these features to be excluded
- [x] NO_SYNC_HTTP - Compile without support for features that require synchronous HTTP which is not supported on profiles like SILVERLIGHT
- [x] NO_FILE
- [x] SILVERLIGHT
- [x] NO_COMPRESSION - Compile without using any System.IO.Compression dependencies.  Will exclude GZip related functionality
- [x] NO_RWLOCK - Compile without any use of ReaderWriterLockSlim - use in conjunction with profiles like SILVERLIGHT where it is not supported.  Will cause all thread safe classes that depend on this to be excluded from the build
- [x] NO_XMLDOM - Compile without any use of XmlDocument and the XML DOM API - use in conjunction with profiles like SILVERLIGHT where it is not supported but other XML APIs are supported
- [x] NO_NORM - Compile without any use of String.Normalize() - use in conjunction with profiles like SILVERLIGHT where it is not supported
- [x] NO_STOPWATCH - Compile without any use of Stopwatch - use in conjunction with profiles like SILVERLIGHT where it is not supported
- [x] UNDEFINED
- [x] NO_STORAGE
- [x] NO_DATAEXTENSIONS
- [x] NO_XMLENTITIES

Where available I added descriptions from [Compiler Symbols.txt](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Compiler%20Symbols.txt)

**Comment by kal** [comment]
Wow, that's a lot! However, now that we are no longer specifically targeting Silverlight or .NET 3.5 there could well be a lot of redundancy in there. My feeling is to take out all conditional sections that are no longer referenced by any of our current target frameworks - if we ever want to reinstate support for a platform such as Silverlight then they can always be added back in again later. Right now I would really like to eliminate as much of the conditional stuff as possible.

**Comment by tpluscode** [comment]
Yes, from what I see most are completely absent from either build target and everything seems to work. Let's remove as many as possible first

**Comment by tpluscode** [comment]
Wow, you killed it yesterday (today?). Which flags are you working on? I could handle NO_ASP/NO_WEB. There are substitutes for some of the pieces missing from netstandard1.4. Or maybe we could add .NET Core target too to have best equivalent of .NET Framework?

**Comment by tpluscode** [comment]
In fact, I'd move the entire VDS.RDF.Web namespace into a separate package targeting only .NET 4.0 given how `System.Web` is probably gone for good on .NET Standard/Core

**Comment by kal** [comment]
Yeah, had a bit of free time today :-)
I'm taking a look at NO_PROXY, so you are good to go ahead and deal with NO_ASP/NO_WEB. 
+1 for moving all the server-side stuff to its own package. I think that there are a couple of dependencies in the core library that might take a bit of untangling.

**Comment by tpluscode** [comment]
’NO_DATA’ flag excludes DataSets from .Net Standard build but they are supported by .Net Core

**Comment by tpluscode** [comment]
I was also looking at `NO_SYSTEMCONFIGURATION` and it's possible to use the `Microsoft.Extensions.Configuration` package and config source packages but I'm not sure what to do about the static nature of `ConfigurationLoader`. Adding a static property for a `IExternalConfiguration` feels kind of icky...

**Comment by kal** [comment]
I agree, but the whole configuration is static anyway... Will one more bit
of ickyness make a difference? ;-)

**Comment by tpluscode** [comment]
I guess not. I'm almost ready with that and there's one more potential improvement. `Microsoft.Extensions.Configuration` doesn't support net40, which is a bummer if someone targetting .NET Framework would want to us that. We could move that to a separate package too, so that any netstandard-compatible consumer can use it.

**Comment by tpluscode** [comment]
Finally I'd also split the `DataTable` code to smth like `dotNetRDF.Data.DataTables` by making the `IGraph#ToDataTable` extension methods. AFAICT this would conclude this PR

**Comment by kal** [comment]
+1 for splitting out the datatables stuff.

I guess that as long as we continue supporting net40 we are stuck with the
configuration stuff.

On 15 Apr 2017 5:56 p.m., "Tomasz Pluskiewicz" <notifications@github.com>
wrote:

Finally I'd also split the DataTable code to smth like
dotNetRDF.Data.DataTables by making the IGraph#ToDataTable extension
methods. AFAICT this would conclude this PR

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dotnetrdf/dotnetrdf/issues/93#issuecomment-294281057>,
or mute the thread
