### ISSUE TITLE
Support DotNet Core

### ISSUE THREAD

**Issue by sjjpo2002** [dotnetrdf/dotnetrdf#95]
Is there any plan to support DotNet Core?

**Comment by tpluscode** [comment]
Yes. Recent prerelease packages include a .NET Standard build. However, due to platform limitations it will not offer the complete feature set of full .NET Framework. Please see how it works for you in the current state

⁣-- 
Tomasz Pluskiewicz ​

**Comment by kal** [comment]
Question answered.
